//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationType
    {
        public ApplicationType()
        {
            this.TrainingHelps = new HashSet<TrainingHelp>();
        }
    
        public int ApplicationTypePK { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Program { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<TrainingHelp> TrainingHelps { get; set; }
    }
}
