//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessProcessTemplateDetail
    {
        public int BusinessProcessTemplateDetailPK { get; set; }
        public Nullable<int> BusinessProcessTemplateFK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> RatingLow { get; set; }
        public Nullable<int> RatingHigh { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> RequiredPassFail { get; set; }
        public Nullable<bool> RequiredDate { get; set; }
        public Nullable<bool> RequiredSignoff { get; set; }
        public Nullable<bool> TollerancePlusRequired { get; set; }
        public Nullable<bool> TolleranceMinusRequired { get; set; }
        public Nullable<bool> XAxisRequired { get; set; }
        public Nullable<bool> XRecordDimensionRequired { get; set; }
        public Nullable<bool> YAxisRequired { get; set; }
        public Nullable<bool> YRecordDimensionRequired { get; set; }
        public Nullable<bool> ZAxisRequired { get; set; }
        public Nullable<bool> ZRecordDimensionRequired { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<bool> DispositionRequired { get; set; }
        public Nullable<bool> QuantityFailRequired { get; set; }
        public Nullable<bool> QuantityPassRequired { get; set; }
        public Nullable<System.DateTime> LoggedDate { get; set; }
    
        public virtual BusinessProcessTemplate BusinessProcessTemplate { get; set; }
        public virtual User User { get; set; }
    }
}
