//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacityPlanningScheduleOpenWorkOrder
    {
        public int CapacityPlanningScheduleOpenWorkOrderPK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> WorkCenterFK { get; set; }
        public Nullable<int> JobNumber { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<int> ParallelResources { get; set; }
        public Nullable<System.DateTime> WorkOrderDueDate { get; set; }
        public Nullable<System.DateTime> WorkOrderStartDate { get; set; }
        public Nullable<decimal> WorkOrderQuantity { get; set; }
        public string TransferBatch { get; set; }
        public byte[] LastAccess { get; set; }
    }
}
