//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificationType
    {
        public CertificationType()
        {
            this.InvoiceLines = new HashSet<InvoiceLine>();
            this.InvoiceLines1 = new HashSet<InvoiceLine>();
            this.InvoiceLines2 = new HashSet<InvoiceLine>();
            this.Parties = new HashSet<Party>();
            this.Parties1 = new HashSet<Party>();
            this.Parties2 = new HashSet<Party>();
            this.SalesOrderLines = new HashSet<SalesOrderLine>();
            this.SalesOrderLines1 = new HashSet<SalesOrderLine>();
            this.SalesOrderLines2 = new HashSet<SalesOrderLine>();
            this.WorkOrders = new HashSet<WorkOrder>();
            this.WorkOrders1 = new HashSet<WorkOrder>();
            this.WorkOrders2 = new HashSet<WorkOrder>();
        }
    
        public int CertificationTypePK { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
        public virtual ICollection<InvoiceLine> InvoiceLines1 { get; set; }
        public virtual ICollection<InvoiceLine> InvoiceLines2 { get; set; }
        public virtual ICollection<Party> Parties { get; set; }
        public virtual ICollection<Party> Parties1 { get; set; }
        public virtual ICollection<Party> Parties2 { get; set; }
        public virtual ICollection<SalesOrderLine> SalesOrderLines { get; set; }
        public virtual ICollection<SalesOrderLine> SalesOrderLines1 { get; set; }
        public virtual ICollection<SalesOrderLine> SalesOrderLines2 { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders1 { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders2 { get; set; }
    }
}
