//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommodityParty
    {
        public int CommodityPartyPK { get; set; }
        public Nullable<int> CommodityFK { get; set; }
        public Nullable<int> PartyFK { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<System.DateTime> CostAsOf { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<decimal> ScrapCredit { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual Party Party { get; set; }
    }
}
