//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDepositLine
    {
        public CustomerDepositLine()
        {
            this.GeneralLedgerDetails = new HashSet<GeneralLedgerDetail>();
        }
    
        public int CustomerDepositLinePK { get; set; }
        public Nullable<int> CustomerDepositFK { get; set; }
        public Nullable<int> CustomerPaymentFK { get; set; }
        public Nullable<int> CustomerFK { get; set; }
        public Nullable<int> FromAccountFK { get; set; }
        public Nullable<int> PaymentMethodFK { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ReferenceNumber { get; set; }
        public string Memo { get; set; }
        public byte[] LastAccess { get; set; }
        public string Name { get; set; }
    
        public virtual CustomerDeposit CustomerDeposit { get; set; }
        public virtual CustomerPayment CustomerPayment { get; set; }
        public virtual GeneralLedgerAccount GeneralLedgerAccount { get; set; }
        public virtual Party Party { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual ICollection<GeneralLedgerDetail> GeneralLedgerDetails { get; set; }
    }
}
