//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPaymentApplyCredit
    {
        public CustomerPaymentApplyCredit()
        {
            this.GeneralLedgerDetails = new HashSet<GeneralLedgerDetail>();
        }
    
        public int CustomerPaymentApplyCreditPK { get; set; }
        public Nullable<int> CustomerPaymentApplyFK { get; set; }
        public Nullable<int> CreditCustomerPaymentFK { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual CustomerPayment CustomerPayment { get; set; }
        public virtual CustomerPaymentApply CustomerPaymentApply { get; set; }
        public virtual ICollection<GeneralLedgerDetail> GeneralLedgerDetails { get; set; }
    }
}
