//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.BulletinMessages = new HashSet<BulletinMessage>();
            this.Projects = new HashSet<Project>();
            this.QualityControls = new HashSet<QualityControl>();
            this.TimeCards = new HashSet<TimeCard>();
            this.Users = new HashSet<User>();
            this.WorkCenters = new HashSet<WorkCenter>();
        }
    
        public int DepartmentPK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Leader { get; set; }
        public string Comment { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<BulletinMessage> BulletinMessages { get; set; }
        public virtual Division Division { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<QualityControl> QualityControls { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<WorkCenter> WorkCenters { get; set; }
    }
}
