//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public Division()
        {
            this.Addresses = new HashSet<Address>();
            this.Bills = new HashSet<Bill>();
            this.BillPayments = new HashSet<BillPayment>();
            this.BillPaymentChecks = new HashSet<BillPaymentCheck>();
            this.Cells = new HashSet<Cell>();
            this.CompanyBenefits = new HashSet<CompanyBenefit>();
            this.CustomerAgings = new HashSet<CustomerAging>();
            this.CustomerPayments = new HashSet<CustomerPayment>();
            this.DaysOffDivisions = new HashSet<DaysOffDivision>();
            this.Departments = new HashSet<Department>();
            this.GeneralJournalEntries = new HashSet<GeneralJournalEntry>();
            this.GeneralLedgerAccounts = new HashSet<GeneralLedgerAccount>();
            this.Invoices = new HashSet<Invoice>();
            this.ItemDivisions = new HashSet<ItemDivision>();
            this.ItemInventoryLocations = new HashSet<ItemInventoryLocation>();
            this.Locations = new HashSet<Location>();
            this.Machines = new HashSet<Machine>();
            this.MachineMaintenanceSchedules = new HashSet<MachineMaintenanceSchedule>();
            this.MachineMaintenanceScheduleRequests = new HashSet<MachineMaintenanceScheduleRequest>();
            this.Manifests = new HashSet<Manifest>();
            this.ManifestLoads = new HashSet<ManifestLoad>();
            this.MRPs = new HashSet<MRP>();
            this.Operations = new HashSet<Operation>();
            this.PartyDivisions = new HashSet<PartyDivision>();
            this.PickListGroups = new HashSet<PickListGroup>();
            this.Projects = new HashSet<Project>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseOrderReceivings = new HashSet<PurchaseOrderReceiving>();
            this.PurchaseOrderRequests = new HashSet<PurchaseOrderRequest>();
            this.PurchaseRFQs = new HashSet<PurchaseRFQ>();
            this.QualityControls = new HashSet<QualityControl>();
            this.Quotes = new HashSet<Quote>();
            this.ReportDivisions = new HashSet<ReportDivision>();
            this.ReportFilterCriterias = new HashSet<ReportFilterCriteria>();
            this.RequestForQuotes = new HashSet<RequestForQuote>();
            this.Routers = new HashSet<Router>();
            this.SalesOrders = new HashSet<SalesOrder>();
            this.Shifts = new HashSet<Shift>();
            this.Sites = new HashSet<Site>();
            this.SupplierAgings = new HashSet<SupplierAging>();
            this.UserDivisions = new HashSet<UserDivision>();
            this.WorkCenters = new HashSet<WorkCenter>();
            this.WorkOrders = new HashSet<WorkOrder>();
            this.WorkOrderNests = new HashSet<WorkOrderNest>();
        }
    
        public int DivisionPK { get; set; }
        public Nullable<int> DivisionParameterFK { get; set; }
        public Nullable<int> OrganizationFK { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<BillPayment> BillPayments { get; set; }
        public virtual ICollection<BillPaymentCheck> BillPaymentChecks { get; set; }
        public virtual ICollection<Cell> Cells { get; set; }
        public virtual ICollection<CompanyBenefit> CompanyBenefits { get; set; }
        public virtual ICollection<CustomerAging> CustomerAgings { get; set; }
        public virtual ICollection<CustomerPayment> CustomerPayments { get; set; }
        public virtual ICollection<DaysOffDivision> DaysOffDivisions { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual DivisionParameter DivisionParameter { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<GeneralJournalEntry> GeneralJournalEntries { get; set; }
        public virtual ICollection<GeneralLedgerAccount> GeneralLedgerAccounts { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<ItemDivision> ItemDivisions { get; set; }
        public virtual ICollection<ItemInventoryLocation> ItemInventoryLocations { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Machine> Machines { get; set; }
        public virtual ICollection<MachineMaintenanceSchedule> MachineMaintenanceSchedules { get; set; }
        public virtual ICollection<MachineMaintenanceScheduleRequest> MachineMaintenanceScheduleRequests { get; set; }
        public virtual ICollection<Manifest> Manifests { get; set; }
        public virtual ICollection<ManifestLoad> ManifestLoads { get; set; }
        public virtual ICollection<MRP> MRPs { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual ICollection<PartyDivision> PartyDivisions { get; set; }
        public virtual ICollection<PickListGroup> PickListGroups { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<PurchaseOrderReceiving> PurchaseOrderReceivings { get; set; }
        public virtual ICollection<PurchaseOrderRequest> PurchaseOrderRequests { get; set; }
        public virtual ICollection<PurchaseRFQ> PurchaseRFQs { get; set; }
        public virtual ICollection<QualityControl> QualityControls { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<ReportDivision> ReportDivisions { get; set; }
        public virtual ICollection<ReportFilterCriteria> ReportFilterCriterias { get; set; }
        public virtual ICollection<RequestForQuote> RequestForQuotes { get; set; }
        public virtual ICollection<Router> Routers { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
        public virtual ICollection<Shift> Shifts { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
        public virtual ICollection<SupplierAging> SupplierAgings { get; set; }
        public virtual ICollection<UserDivision> UserDivisions { get; set; }
        public virtual ICollection<WorkCenter> WorkCenters { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        public virtual ICollection<WorkOrderNest> WorkOrderNests { get; set; }
    }
}
