//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicRequestForQuoteLine
    {
        public int ElectronicRequestForQuoteLinePK { get; set; }
        public Nullable<int> ElectronicRequestForQuoteFK { get; set; }
        public Nullable<int> CustomerFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> QuoteFK { get; set; }
        public Nullable<int> RequestForQuoteFK { get; set; }
        public Nullable<int> RequestForQuoteLineFK { get; set; }
        public Nullable<bool> AddressMismatch { get; set; }
        public Nullable<bool> PartNumberMismatch { get; set; }
        public Nullable<bool> RevisionMismatch { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> StockLength { get; set; }
        public Nullable<decimal> StockWidth { get; set; }
        public string BillToCode { get; set; }
        public string ImportedRevision { get; set; }
        public string Revision { get; set; }
        public string ShipToCode { get; set; }
        public string FOB { get; set; }
        public string PartNumber { get; set; }
        public string VendorPartNumber { get; set; }
        public string Description { get; set; }
        public string CadFile { get; set; }
        public string Comment { get; set; }
        public string CustomDescription { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string AddressAlt { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string ShippingName { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingAddress3 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingZip { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ElectronicRequestForQuote ElectronicRequestForQuote { get; set; }
        public virtual Party Party { get; set; }
        public virtual Item Item { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual RequestForQuote RequestForQuote { get; set; }
        public virtual RequestForQuoteLine RequestForQuoteLine { get; set; }
    }
}
