//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicRequestForQuote
    {
        public ElectronicRequestForQuote()
        {
            this.ElectronicRequestForQuoteLines = new HashSet<ElectronicRequestForQuoteLine>();
        }
    
        public int ElectronicRequestForQuotePK { get; set; }
        public Nullable<int> CustomerFK { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string DocumentType { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual ICollection<ElectronicRequestForQuoteLine> ElectronicRequestForQuoteLines { get; set; }
    }
}
