//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentTypeAccrual
    {
        public int EmploymentTypeAccrualPK { get; set; }
        public Nullable<int> EmploymentTypeFK { get; set; }
        public Nullable<int> TimeClockAccrualFK { get; set; }
        public Nullable<int> AccrualIntervalType { get; set; }
        public Nullable<int> DaysToActivate { get; set; }
        public Nullable<decimal> AccrualRate { get; set; }
        public Nullable<decimal> AccrualInterval { get; set; }
        public Nullable<decimal> InitialAccrualAmount { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public Nullable<decimal> TotalAccrualAmount { get; set; }
        public Nullable<bool> CarryBalanceForwardYearly { get; set; }
        public Nullable<bool> EnableMax { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual EmploymentType EmploymentType { get; set; }
        public virtual TimeClockAccrual TimeClockAccrual { get; set; }
    }
}
