//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form1099Report
    {
        public Form1099Report()
        {
            this.Form1099ReportParty = new HashSet<Form1099ReportParty>();
        }
    
        public int Form1099ReportPK { get; set; }
        public Nullable<int> FiscalCalendarFK { get; set; }
        public Nullable<int> PayerAddressFK { get; set; }
        public Nullable<int> PayerAddressStateFK { get; set; }
        public Nullable<int> PayerAddressCountryFK { get; set; }
        public Nullable<int> PayerAddressRegionFK { get; set; }
        public string PayerName { get; set; }
        public string PayerAddress1 { get; set; }
        public string PayerAddress2 { get; set; }
        public string PayerAddressAlt { get; set; }
        public string PayerAddressCity { get; set; }
        public string PayerAddressZipCode { get; set; }
        public string PayerPhone { get; set; }
        public string PayerTaxIdOrSSN { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Country Country { get; set; }
        public virtual FiscalCalendar FiscalCalendar { get; set; }
        public virtual Region Region { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<Form1099ReportParty> Form1099ReportParty { get; set; }
    }
}
