//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreightClass
    {
        public FreightClass()
        {
            this.ManifestLines = new HashSet<ManifestLine>();
        }
    
        public int FreightClassPK { get; set; }
        public string Cost { get; set; }
        public string Name { get; set; }
        public string WeightRangePerCubicFoot { get; set; }
        public string Notes { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<ManifestLine> ManifestLines { get; set; }
    }
}
