//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRDependent
    {
        public int HRDependentPK { get; set; }
        public Nullable<int> DependentTypeFK { get; set; }
        public Nullable<int> RelationshipFK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string DependentName { get; set; }
        public string Note { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserCodeItem UserCodeItem { get; set; }
        public virtual UserCodeItem UserCodeItem1 { get; set; }
    }
}
