//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREvaluationType
    {
        public HREvaluationType()
        {
            this.HREvaluations = new HashSet<HREvaluation>();
            this.HREvaluationCategories = new HashSet<HREvaluationCategory>();
        }
    
        public int HREvaluationTypePK { get; set; }
        public byte[] LastAccess { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<HREvaluation> HREvaluations { get; set; }
        public virtual ICollection<HREvaluationCategory> HREvaluationCategories { get; set; }
    }
}
