//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPersonalInfo
    {
        public int HRPersonalInfoPK { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> SexMale { get; set; }
        public string SSN { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string FormerName { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public string SpouseName { get; set; }
        public Nullable<System.DateTime> SpouseDateOfBirth { get; set; }
        public string SpouseSSN { get; set; }
        public byte[] LastAccess { get; set; }
    }
}
