//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRTraining
    {
        public int HRTrainingPK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> TraningClassFK { get; set; }
        public Nullable<int> SubTrainingClassFK { get; set; }
        public Nullable<int> GradeFK { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Location { get; set; }
        public string Instructor { get; set; }
        public string Comments { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserCodeItem UserCodeItem { get; set; }
        public virtual UserCodeItem UserCodeItem1 { get; set; }
        public virtual UserCodeItem UserCodeItem2 { get; set; }
    }
}
