//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportExportType
    {
        public ImportExportType()
        {
            this.ImportExportScripts = new HashSet<ImportExportScript>();
        }
    
        public int ImportExportTypePK { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ImportExportScript> ImportExportScripts { get; set; }
    }
}
