//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePackaging
    {
        public int InvoicePackagingPK { get; set; }
        public Nullable<int> InvoiceLineFK { get; set; }
        public Nullable<int> ItemPackagingFK { get; set; }
        public Nullable<decimal> BoxQuantity { get; set; }
        public Nullable<int> QuantityOfBoxes { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual InvoiceLine InvoiceLine { get; set; }
        public virtual ItemPackaging ItemPackaging { get; set; }
    }
}
