//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLine
    {
        public InvoiceLine()
        {
            this.InvoicePackagings = new HashSet<InvoicePackaging>();
            this.ItemSerialNumbers = new HashSet<ItemSerialNumber>();
            this.Kits = new HashSet<Kit>();
            this.ManifestLines = new HashSet<ManifestLine>();
        }
    
        public int InvoiceLinePK { get; set; }
        public Nullable<int> AlternativeUnitOfMeasureSetFK { get; set; }
        public Nullable<int> GeneralLedgerFK { get; set; }
        public Nullable<int> InvoiceFK { get; set; }
        public Nullable<int> InvoiceLineItemTypeFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> HardwareCertificationFK { get; set; }
        public Nullable<int> MaterialCertificationFK { get; set; }
        public Nullable<int> OutsideProcessingCertificationFK { get; set; }
        public Nullable<int> QuoteFK { get; set; }
        public Nullable<int> UnitOfMeasureSetFK { get; set; }
        public Nullable<int> ShippingAddressFK { get; set; }
        public Nullable<int> SalesOrderLineLotFK { get; set; }
        public Nullable<int> JobNumber { get; set; }
        public Nullable<int> LineReferenceNumber { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> SalesOrderLineReferenceNumber { get; set; }
        public Nullable<bool> LotPrice { get; set; }
        public Nullable<bool> CertificationOfPerformanceRequired { get; set; }
        public Nullable<bool> HardwareApprovedSupplierRequired { get; set; }
        public Nullable<bool> MaterialApprovedSupplierRequired { get; set; }
        public Nullable<bool> NonCommissionable { get; set; }
        public Nullable<bool> OutsideProcessingApprovedSupplierRequired { get; set; }
        public Nullable<bool> RequiresSource { get; set; }
        public Nullable<bool> Resale { get; set; }
        public Nullable<bool> RMA { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> SalesOrderLineLotDateStamp { get; set; }
        public Nullable<System.DateTime> PromiseDate { get; set; }
        public Nullable<decimal> CommissionOverridePercentage { get; set; }
        public Nullable<decimal> AlternativeQuantity { get; set; }
        public Nullable<decimal> AlternativePrice { get; set; }
        public Nullable<decimal> StockLength { get; set; }
        public Nullable<decimal> StockWidth { get; set; }
        public Nullable<decimal> PieceWeight { get; set; }
        public Nullable<decimal> VendorUnit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ExtendedAmount { get; set; }
        public Nullable<decimal> ForeignCurrencyPrice { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> MarkupPercentage { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> QuantityOrdered { get; set; }
        public string Revision { get; set; }
        public string CreditNumber { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string RMANumber { get; set; }
        public string RMAReturnNumber { get; set; }
        public string MemoInvoiceNumber { get; set; }
        public string ShippingAddressName { get; set; }
        public string PartNumber { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingAddressAlt { get; set; }
        public string ShippingAddressCity { get; set; }
        public string ShippingAddressZipCode { get; set; }
        public string SalesTax1Name { get; set; }
        public Nullable<decimal> SalesTax1Rate { get; set; }
        public string SalesTaxType1Description { get; set; }
        public string SalesTax2Name { get; set; }
        public Nullable<decimal> SalesTax2Rate { get; set; }
        public string SalesTaxType2Description { get; set; }
        public string SalesTax3Name { get; set; }
        public Nullable<decimal> SalesTax3Rate { get; set; }
        public string SalesTaxType3Description { get; set; }
        public string SalesTax4Name { get; set; }
        public Nullable<decimal> SalesTax4Rate { get; set; }
        public string SalesTaxType4Description { get; set; }
        public string CustomDescription { get; set; }
        public string Notes { get; set; }
        public string ShippingNotes { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> WorkOrderNumber { get; set; }
        public Nullable<decimal> InventoryCost { get; set; }
        public Nullable<decimal> BoxQuantity { get; set; }
        public Nullable<decimal> CutLength { get; set; }
        public Nullable<decimal> CutWidth { get; set; }
        public Nullable<bool> CertificationsRequired { get; set; }
        public Nullable<bool> FirstArticleRequired { get; set; }
        public Nullable<bool> Printed { get; set; }
        public string LotNumber { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<int> LocationNumber { get; set; }
        public string CustomerLineNumber { get; set; }
        public string UserDefined { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual CertificationType CertificationType { get; set; }
        public virtual CertificationType CertificationType1 { get; set; }
        public virtual CertificationType CertificationType2 { get; set; }
        public virtual GeneralLedgerAccount GeneralLedgerAccount { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual UnitOfMeasureSet UnitOfMeasureSet { get; set; }
        public virtual InvoiceLineItemType InvoiceLineItemType { get; set; }
        public virtual Item Item { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual SalesOrderLineLot SalesOrderLineLot { get; set; }
        public virtual UnitOfMeasureSet UnitOfMeasureSet1 { get; set; }
        public virtual ICollection<InvoicePackaging> InvoicePackagings { get; set; }
        public virtual ICollection<ItemSerialNumber> ItemSerialNumbers { get; set; }
        public virtual ICollection<Kit> Kits { get; set; }
        public virtual ICollection<ManifestLine> ManifestLines { get; set; }
    }
}
