//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInventoryWorkSheetItem
    {
        public int ItemInventoryWorkSheetItemPK { get; set; }
        public Nullable<int> ItemInventoryWorkSheetFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> ItemInventoryLocation { get; set; }
        public Nullable<int> PartyFK { get; set; }
        public string Description { get; set; }
        public string PartNumber { get; set; }
        public string Revision { get; set; }
        public string ItemInventoryLocationDescription { get; set; }
        public string LotNumber { get; set; }
        public Nullable<decimal> PhysicalCount { get; set; }
        public Nullable<decimal> QuantityOnHand { get; set; }
        public Nullable<decimal> StockLength { get; set; }
        public Nullable<decimal> StockWidth { get; set; }
        public Nullable<decimal> LastCost { get; set; }
        public Nullable<decimal> CurrentStandardCost { get; set; }
        public Nullable<decimal> StandardCost { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsPostable { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> CatalogFK { get; set; }
        public Nullable<int> CatalogCategoryFK { get; set; }
        public string RouterNumber { get; set; }
        public Nullable<decimal> TotalQuantityOnHand { get; set; }
        public Nullable<decimal> AverageCost { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual CatalogCategory CatalogCategory { get; set; }
        public virtual Item Item { get; set; }
        public virtual ItemInventoryWorkSheet ItemInventoryWorkSheet { get; set; }
        public virtual Party Party { get; set; }
    }
}
