//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemClass
    {
        public ItemClass()
        {
            this.Discounts = new HashSet<Discount>();
            this.Items = new HashSet<Item>();
            this.Projects = new HashSet<Project>();
        }
    
        public int ItemClassPK { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<Discount> Discounts { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
