//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDivision
    {
        public int ItemDivisionPK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<decimal> QuantityOnHand { get; set; }
        public Nullable<decimal> QuantityReserved { get; set; }
        public Nullable<decimal> QuantityDemand { get; set; }
        public Nullable<decimal> QuantityWorkInProcess { get; set; }
        public Nullable<decimal> QuantityPull { get; set; }
        public Nullable<decimal> QuantityOrdered { get; set; }
        public Nullable<decimal> QuantityOnDock { get; set; }
        public Nullable<decimal> StandardCost { get; set; }
        public Nullable<decimal> LandedCost { get; set; }
        public Nullable<decimal> LastCost { get; set; }
        public Nullable<decimal> AverageCost { get; set; }
        public Nullable<decimal> FIFOCost { get; set; }
        public Nullable<System.DateTime> LastOrderDate { get; set; }
        public Nullable<System.DateTime> LastTransactionDate { get; set; }
        public Nullable<System.DateTime> LastCostDate { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual Item Item { get; set; }
    }
}
