//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMasterProductionSchedule
    {
        public int ItemMPSPK { get; set; }
        public Nullable<int> CalendarPeriodFK { get; set; }
        public Nullable<int> FiscalCalendarFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<System.DateTime> Date01 { get; set; }
        public Nullable<System.DateTime> Date02 { get; set; }
        public Nullable<System.DateTime> Date03 { get; set; }
        public Nullable<System.DateTime> Date04 { get; set; }
        public Nullable<System.DateTime> Date05 { get; set; }
        public Nullable<System.DateTime> Date06 { get; set; }
        public Nullable<System.DateTime> Date07 { get; set; }
        public Nullable<System.DateTime> Date08 { get; set; }
        public Nullable<System.DateTime> Date09 { get; set; }
        public Nullable<System.DateTime> Date10 { get; set; }
        public Nullable<System.DateTime> Date11 { get; set; }
        public Nullable<System.DateTime> Date12 { get; set; }
        public Nullable<System.DateTime> Date13 { get; set; }
        public Nullable<System.DateTime> Date14 { get; set; }
        public Nullable<System.DateTime> Date15 { get; set; }
        public Nullable<System.DateTime> Date16 { get; set; }
        public Nullable<System.DateTime> Date17 { get; set; }
        public Nullable<System.DateTime> Date18 { get; set; }
        public Nullable<System.DateTime> Date19 { get; set; }
        public Nullable<System.DateTime> Date20 { get; set; }
        public Nullable<System.DateTime> Date21 { get; set; }
        public Nullable<System.DateTime> Date22 { get; set; }
        public Nullable<System.DateTime> Date23 { get; set; }
        public Nullable<System.DateTime> Date24 { get; set; }
        public Nullable<System.DateTime> Date25 { get; set; }
        public Nullable<System.DateTime> Date26 { get; set; }
        public Nullable<decimal> Quantity01 { get; set; }
        public Nullable<decimal> Quantity02 { get; set; }
        public Nullable<decimal> Quantity03 { get; set; }
        public Nullable<decimal> Quantity04 { get; set; }
        public Nullable<decimal> Quantity05 { get; set; }
        public Nullable<decimal> Quantity06 { get; set; }
        public Nullable<decimal> Quantity07 { get; set; }
        public Nullable<decimal> Quantity08 { get; set; }
        public Nullable<decimal> Quantity09 { get; set; }
        public Nullable<decimal> Quantity10 { get; set; }
        public Nullable<decimal> Quantity11 { get; set; }
        public Nullable<decimal> Quantity12 { get; set; }
        public Nullable<decimal> Quantity13 { get; set; }
        public Nullable<decimal> Quantity14 { get; set; }
        public Nullable<decimal> Quantity15 { get; set; }
        public Nullable<decimal> Quantity16 { get; set; }
        public Nullable<decimal> Quantity17 { get; set; }
        public Nullable<decimal> Quantity18 { get; set; }
        public Nullable<decimal> Quantity19 { get; set; }
        public Nullable<decimal> Quantity20 { get; set; }
        public Nullable<decimal> Quantity21 { get; set; }
        public Nullable<decimal> Quantity22 { get; set; }
        public Nullable<decimal> Quantity23 { get; set; }
        public Nullable<decimal> Quantity24 { get; set; }
        public Nullable<decimal> Quantity25 { get; set; }
        public Nullable<decimal> Quantity26 { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual CalendarPeriod CalendarPeriod { get; set; }
        public virtual FiscalCalendar FiscalCalendar { get; set; }
        public virtual Item Item { get; set; }
    }
}
