//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineSetup
    {
        public MachineSetup()
        {
            this.Items = new HashSet<Item>();
            this.ItemMachines = new HashSet<ItemMachine>();
            this.Machines = new HashSet<Machine>();
            this.MachineSetupStockSizes = new HashSet<MachineSetupStockSize>();
            this.MachineSetupTurrets = new HashSet<MachineSetupTurret>();
        }
    
        public int MachineSetupPK { get; set; }
        public Nullable<int> MachineSetupTypeFK { get; set; }
        public string MachineId { get; set; }
        public string Description { get; set; }
        public decimal TopTrim { get; set; }
        public decimal BottomTrim { get; set; }
        public decimal LeftTrim { get; set; }
        public decimal RightTrim { get; set; }
        public decimal PartsSpacing { get; set; }
        public string ManufacturingDetailSpecification { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<bool> DefaultMachineSetup { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<ItemMachine> ItemMachines { get; set; }
        public virtual ICollection<Machine> Machines { get; set; }
        public virtual MachineSetupType MachineSetupType { get; set; }
        public virtual ICollection<MachineSetupStockSize> MachineSetupStockSizes { get; set; }
        public virtual ICollection<MachineSetupTurret> MachineSetupTurrets { get; set; }
    }
}
