//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public Machine()
        {
            this.CellMachines = new HashSet<CellMachine>();
            this.EngineeringChangeRequests = new HashSet<EngineeringChangeRequest>();
            this.FixedAssets = new HashSet<FixedAsset>();
            this.MachineMaintenanceSchedules = new HashSet<MachineMaintenanceSchedule>();
            this.MachineMaintenanceScheduleRequests = new HashSet<MachineMaintenanceScheduleRequest>();
            this.MachineMaintenanceScheduleTypes = new HashSet<MachineMaintenanceScheduleType>();
            this.MachineMaintenanceScheduleWorkOrders = new HashSet<MachineMaintenanceScheduleWorkOrder>();
            this.MachineUsageReadings = new HashSet<MachineUsageReading>();
            this.Operations = new HashSet<Operation>();
            this.QuoteAssemblyMachines = new HashSet<QuoteAssemblyMachine>();
            this.RouterWorkCenterMachines = new HashSet<RouterWorkCenterMachine>();
            this.ScheduleDetails = new HashSet<ScheduleDetail>();
            this.ScheduleResources = new HashSet<ScheduleResource>();
            this.SpareParts = new HashSet<SparePart>();
            this.WorkOrderCollections = new HashSet<WorkOrderCollection>();
            this.WorkOrderPrograms = new HashSet<WorkOrderProgram>();
        }
    
        public int MachinePK { get; set; }
        public int WorkCenterFK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public Nullable<int> EmployeeShift1FK { get; set; }
        public Nullable<int> EmployeeShift2FK { get; set; }
        public Nullable<int> EmployeeShift3FK { get; set; }
        public Nullable<int> MachineCategoryFK { get; set; }
        public Nullable<int> MachineStatusFK { get; set; }
        public Nullable<int> MachineTypeFK { get; set; }
        public Nullable<int> ManufacturerFK { get; set; }
        public Nullable<int> PictureFK { get; set; }
        public Nullable<int> SiteFK { get; set; }
        public Nullable<int> VendorFK { get; set; }
        public Nullable<int> SchedulingModeFK { get; set; }
        public Nullable<int> ExpectedAvailabilityTime { get; set; }
        public Nullable<int> ModelYear { get; set; }
        public Nullable<bool> NonProductionAsset { get; set; }
        public string AssetNumber { get; set; }
        public string MachineDescription { get; set; }
        public string MachineNumber { get; set; }
        public string MeterUnitName { get; set; }
        public string ModelNumber { get; set; }
        public string Notes { get; set; }
        public string Purpose { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<decimal> CapacityHours { get; set; }
        public Nullable<decimal> HourlyOverHead { get; set; }
        public Nullable<decimal> LagTime { get; set; }
        public Nullable<decimal> LastMeterReading { get; set; }
        public Nullable<decimal> MeterWeeklyConsuming { get; set; }
        public Nullable<decimal> PercentOfProductivity { get; set; }
        public Nullable<decimal> MondayHours { get; set; }
        public Nullable<decimal> TuesdayHours { get; set; }
        public Nullable<decimal> WednesdayHours { get; set; }
        public Nullable<decimal> ThursdayHours { get; set; }
        public Nullable<decimal> FridayHours { get; set; }
        public Nullable<decimal> SaturdayHours { get; set; }
        public Nullable<decimal> SundayHours { get; set; }
        public Nullable<bool> Monday { get; set; }
        public Nullable<bool> Tuesday { get; set; }
        public Nullable<bool> Wednesday { get; set; }
        public Nullable<bool> Thursday { get; set; }
        public Nullable<bool> Friday { get; set; }
        public Nullable<bool> Saturday { get; set; }
        public Nullable<bool> Sunday { get; set; }
        public Nullable<System.DateTime> AvailableIn { get; set; }
        public Nullable<System.DateTime> LastMaintenanceDate { get; set; }
        public Nullable<System.DateTime> LastMeterReadingDate { get; set; }
        public Nullable<System.DateTime> WarrantyStartDate { get; set; }
        public Nullable<System.DateTime> WarrantyEndDate { get; set; }
        public Nullable<int> MondayStartTimeMinutes { get; set; }
        public Nullable<int> TuesdayStartTimeMinutes { get; set; }
        public Nullable<int> WednesdayStarTimeMinutes { get; set; }
        public Nullable<int> ThursdayStartTimeMinutes { get; set; }
        public Nullable<int> FridayStartTimeMinutes { get; set; }
        public Nullable<int> SaturdayStartTimeMinutes { get; set; }
        public Nullable<int> SundayStartTimeMinutes { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> MachineSetupFK { get; set; }
        public Nullable<decimal> WONestSetupTime { get; set; }
    
        public virtual ICollection<CellMachine> CellMachines { get; set; }
        public virtual Division Division { get; set; }
        public virtual ICollection<EngineeringChangeRequest> EngineeringChangeRequests { get; set; }
        public virtual ICollection<FixedAsset> FixedAssets { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual MachineCategory MachineCategory { get; set; }
        public virtual MachineSetup MachineSetup { get; set; }
        public virtual MachineStatu MachineStatu { get; set; }
        public virtual MachineType MachineType { get; set; }
        public virtual Party Party { get; set; }
        public virtual SchedulingMode SchedulingMode { get; set; }
        public virtual Site Site { get; set; }
        public virtual Party Party1 { get; set; }
        public virtual WorkCenter WorkCenter { get; set; }
        public virtual ICollection<MachineMaintenanceSchedule> MachineMaintenanceSchedules { get; set; }
        public virtual ICollection<MachineMaintenanceScheduleRequest> MachineMaintenanceScheduleRequests { get; set; }
        public virtual ICollection<MachineMaintenanceScheduleType> MachineMaintenanceScheduleTypes { get; set; }
        public virtual ICollection<MachineMaintenanceScheduleWorkOrder> MachineMaintenanceScheduleWorkOrders { get; set; }
        public virtual ICollection<MachineUsageReading> MachineUsageReadings { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual ICollection<QuoteAssemblyMachine> QuoteAssemblyMachines { get; set; }
        public virtual ICollection<RouterWorkCenterMachine> RouterWorkCenterMachines { get; set; }
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
        public virtual ICollection<ScheduleResource> ScheduleResources { get; set; }
        public virtual ICollection<SparePart> SpareParts { get; set; }
        public virtual ICollection<WorkOrderCollection> WorkOrderCollections { get; set; }
        public virtual ICollection<WorkOrderProgram> WorkOrderPrograms { get; set; }
    }
}
