//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineMaintenanceScheduleWorkOrder
    {
        public MachineMaintenanceScheduleWorkOrder()
        {
            this.Documents = new HashSet<Document>();
            this.MachineMaintenanceRequiredItems = new HashSet<MachineMaintenanceRequiredItem>();
            this.MachineMaintenanceScheduleRequests = new HashSet<MachineMaintenanceScheduleRequest>();
            this.MachineMaintenanceScheduleWorkOrderActivities = new HashSet<MachineMaintenanceScheduleWorkOrderActivity>();
            this.TaskActivities = new HashSet<TaskActivity>();
        }
    
        public int MachineMaintenanceScheduleWorkOrderPK { get; set; }
        public Nullable<int> ContractorFK { get; set; }
        public Nullable<int> CreatorFK { get; set; }
        public Nullable<int> CycleDueByTypeFK { get; set; }
        public Nullable<int> CycleEstimateDownTimeTypeFK { get; set; }
        public Nullable<int> CycleRepeatTypeFK { get; set; }
        public Nullable<int> FailureTypeFK { get; set; }
        public Nullable<int> InternalWorkerFK { get; set; }
        public Nullable<int> MachineFK { get; set; }
        public Nullable<int> MachineMaintenancePriorityFK { get; set; }
        public Nullable<int> MachineMaintenanceScheduleFK { get; set; }
        public Nullable<int> MachineMaintenanceScheduleTypeFK { get; set; }
        public Nullable<int> MachineMaintenanceScheduleWorkOrderStatusFK { get; set; }
        public Nullable<int> ReminderFK { get; set; }
        public Nullable<int> SupervisorFK { get; set; }
        public Nullable<int> CycleDueBy { get; set; }
        public Nullable<int> CycleEstimateDownTime { get; set; }
        public Nullable<int> CycleRepeats { get; set; }
        public Nullable<int> MachineMaintenanceScheduleWorkOrderNumber { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public string DisplayKey { get; set; }
        public string Code { get; set; }
        public string CycleStartAt { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> Progress { get; set; }
        public Nullable<decimal> WorkHours { get; set; }
        public Nullable<decimal> WorkHourRate { get; set; }
        public Nullable<System.DateTime> CycleStartFrom { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> DueDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<System.DateTime> LastRunDateTime { get; set; }
        public Nullable<System.DateTime> ProjectedStartDate { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public string Instructions { get; set; }
        public string Notes { get; set; }
        public string ResultNotes { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual FailureType FailureType { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual MachineMaintenanceCycleType MachineMaintenanceCycleType { get; set; }
        public virtual MachineMaintenanceCycleType MachineMaintenanceCycleType1 { get; set; }
        public virtual MachineMaintenanceCycleType MachineMaintenanceCycleType2 { get; set; }
        public virtual MachineMaintenancePriority MachineMaintenancePriority { get; set; }
        public virtual MachineMaintenanceReminder MachineMaintenanceReminder { get; set; }
        public virtual ICollection<MachineMaintenanceRequiredItem> MachineMaintenanceRequiredItems { get; set; }
        public virtual MachineMaintenanceSchedule MachineMaintenanceSchedule { get; set; }
        public virtual ICollection<MachineMaintenanceScheduleRequest> MachineMaintenanceScheduleRequests { get; set; }
        public virtual MachineMaintenanceScheduleType MachineMaintenanceScheduleType { get; set; }
        public virtual MachineMaintenanceScheduleWorkOrderStatu MachineMaintenanceScheduleWorkOrderStatu { get; set; }
        public virtual Party Party { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<MachineMaintenanceScheduleWorkOrderActivity> MachineMaintenanceScheduleWorkOrderActivities { get; set; }
        public virtual ICollection<TaskActivity> TaskActivities { get; set; }
    }
}
