//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManifestDropLocation
    {
        public int ManifestDropLocationPK { get; set; }
        public Nullable<int> ManifestFK { get; set; }
        public Nullable<int> CustomerFK { get; set; }
        public Nullable<int> AddressFK { get; set; }
        public Nullable<int> DeliveryTime { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Manifest Manifest { get; set; }
        public virtual Party Party { get; set; }
    }
}
