//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manifest
    {
        public Manifest()
        {
            this.Documents = new HashSet<Document>();
            this.ManifestDropLocations = new HashSet<ManifestDropLocation>();
            this.ManifestLines = new HashSet<ManifestLine>();
        }
    
        public int ManifestPK { get; set; }
        public Nullable<int> BillingAddressFK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public Nullable<int> AcceptedByFK { get; set; }
        public Nullable<int> FreightCodeFK { get; set; }
        public Nullable<int> ManifestStatusFK { get; set; }
        public Nullable<int> PartyFK { get; set; }
        public Nullable<int> ShippingAddressFK { get; set; }
        public Nullable<int> ShipViaFK { get; set; }
        public Nullable<int> VendorFK { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<int> ManifestNumber { get; set; }
        public Nullable<int> NumberOfPackages { get; set; }
        public Nullable<bool> AssignedToLoader { get; set; }
        public Nullable<bool> Exported { get; set; }
        public Nullable<bool> InspectedLoad { get; set; }
        public Nullable<bool> InvoicedFreight { get; set; }
        public Nullable<bool> PrintTopLevelPackaging { get; set; }
        public Nullable<bool> ReleasedToDispatch { get; set; }
        public Nullable<bool> ReservedByVendor { get; set; }
        public Nullable<bool> Shipped { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<System.DateTime> DateInvoiced { get; set; }
        public Nullable<System.DateTime> DateInspected { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
        public Nullable<System.DateTime> DateReserved { get; set; }
        public Nullable<System.DateTime> DateShipped { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<decimal> CODAmount { get; set; }
        public Nullable<decimal> CollectionAmount { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> AdditionalWeight { get; set; }
        public Nullable<decimal> RateActual { get; set; }
        public Nullable<decimal> RateQuoted { get; set; }
        public string DriversPhone { get; set; }
        public string DriversName { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string UserDefinedPO { get; set; }
        public string VehicleID { get; set; }
        public string CarrierName { get; set; }
        public string TrackingNumber { get; set; }
        public string VarianceReason { get; set; }
        public string Comments { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual Division Division { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual FreightCode FreightCode { get; set; }
        public virtual User User { get; set; }
        public virtual ManifestStatu ManifestStatu { get; set; }
        public virtual Party Party { get; set; }
        public virtual ShipVia ShipVia { get; set; }
        public virtual Party Party1 { get; set; }
        public virtual ICollection<ManifestDropLocation> ManifestDropLocations { get; set; }
        public virtual ICollection<ManifestLine> ManifestLines { get; set; }
    }
}
