//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManifestLoad
    {
        public ManifestLoad()
        {
            this.Documents = new HashSet<Document>();
            this.ManifestLoadDetails = new HashSet<ManifestLoadDetail>();
        }
    
        public int ManifestLoadPK { get; set; }
        public Nullable<int> BrokerFK { get; set; }
        public Nullable<int> CarrierFK { get; set; }
        public Nullable<int> DispatcherFK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public Nullable<int> LoaderFK { get; set; }
        public Nullable<int> ManifestLoadTypeFK { get; set; }
        public Nullable<int> ManifestLoadNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> DeliverDate { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> InspectedDate { get; set; }
        public Nullable<System.DateTime> ReservedDate { get; set; }
        public Nullable<System.DateTime> FreightInvoiceDate { get; set; }
        public Nullable<System.DateTime> ComfirmedTime { get; set; }
        public string AcceptedBy { get; set; }
        public string Description { get; set; }
        public string TrackingNumber { get; set; }
        public string TrailerNotes { get; set; }
        public string VarianceReason { get; set; }
        public Nullable<bool> ReleasedToDispatch { get; set; }
        public Nullable<bool> AssignedToLoader { get; set; }
        public Nullable<bool> Reserved { get; set; }
        public Nullable<bool> Inspected { get; set; }
        public Nullable<bool> Shipped { get; set; }
        public Nullable<bool> FreightInvoiced { get; set; }
        public Nullable<decimal> PickListWeight { get; set; }
        public Nullable<decimal> RateActual { get; set; }
        public Nullable<decimal> RateQuoted { get; set; }
        public byte[] LastAccess { get; set; }
        public string UserDefined { get; set; }
        public Nullable<int> TrailerTypeFK { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Party Party { get; set; }
        public virtual Party Party1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ManifestLoadType ManifestLoadType { get; set; }
        public virtual TrailerType TrailerType { get; set; }
        public virtual ICollection<ManifestLoadDetail> ManifestLoadDetails { get; set; }
    }
}
