//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRPDetail
    {
        public int MRPDetailsPK { get; set; }
        public Nullable<int> MRPFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> ParentRouterFK { get; set; }
        public Nullable<int> RouterFK { get; set; }
        public Nullable<int> SalesOrderFK { get; set; }
        public Nullable<int> SalesOrderLineFK { get; set; }
        public Nullable<int> SalesOrderLineLotFK { get; set; }
        public Nullable<int> WorkOrderFK { get; set; }
        public Nullable<int> WorkOrderReleaseFK { get; set; }
        public Nullable<int> LineReferenceNumber { get; set; }
        public Nullable<int> BlanketPONumber { get; set; }
        public Nullable<decimal> NetRequirements { get; set; }
        public Nullable<bool> ForecastLine { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> WorkOrderDueDate { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public Nullable<System.DateTime> MoveDate { get; set; }
        public string CustomerName { get; set; }
        public string Description { get; set; }
        public string JobNumber { get; set; }
        public string ItemNumber { get; set; }
        public string ParentRouterPartNumber { get; set; }
        public string PartNumber { get; set; }
        public string Revision { get; set; }
        public string WorkOrderNumber { get; set; }
        public Nullable<decimal> QuantityCompleted { get; set; }
        public Nullable<decimal> QuantityDemand { get; set; }
        public Nullable<decimal> QuantityFab { get; set; }
        public Nullable<decimal> QuantityFrequency { get; set; }
        public Nullable<decimal> QuantityNeeded { get; set; }
        public Nullable<decimal> QuantityOnHand { get; set; }
        public Nullable<decimal> QuantityOrdered { get; set; }
        public Nullable<decimal> QuantityWorkInProcess { get; set; }
        public Nullable<decimal> RunningInventoryOnHand { get; set; }
        public Nullable<decimal> StockLength { get; set; }
        public Nullable<decimal> StockWidth { get; set; }
        public Nullable<bool> ProposedWorkOrder { get; set; }
        public Nullable<bool> ProposedPurchaseOrder { get; set; }
        public Nullable<bool> BillOfMaterial { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public Nullable<decimal> SubOnHand { get; set; }
        public Nullable<decimal> SubOnHandDemand { get; set; }
        public string DefaultPartyName { get; set; }
        public string WorkCenter { get; set; }
        public Nullable<int> DefaultPartyId { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<bool> ExplodeProposed { get; set; }
        public Nullable<bool> ProposedWorkOrderRequirement { get; set; }
        public Nullable<System.DateTime> OrderByDate { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual MRP MRP { get; set; }
        public virtual Router Router { get; set; }
        public virtual Router Router1 { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual SalesOrderLine SalesOrderLine { get; set; }
        public virtual SalesOrderLineLot SalesOrderLineLot { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual WorkOrderRelease WorkOrderRelease { get; set; }
    }
}
