//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationFormulaVariable
    {
        public OperationFormulaVariable()
        {
            this.QuoteAssemblyFormulaVariables = new HashSet<QuoteAssemblyFormulaVariable>();
        }
    
        public int OperationFormulaVariablePK { get; set; }
        public Nullable<int> OperationFormulaFK { get; set; }
        public Nullable<int> OperationFormulaVariableTypeFK { get; set; }
        public Nullable<int> LookupTableTypeFK { get; set; }
        public Nullable<int> DefaultLookupTableFK { get; set; }
        public Nullable<bool> Required { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> DefaultValue { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    
        public virtual LookupTable LookupTable { get; set; }
        public virtual LookupTableType LookupTableType { get; set; }
        public virtual OperationFormula OperationFormula { get; set; }
        public virtual OperationFormulaVariableType OperationFormulaVariableType { get; set; }
        public virtual ICollection<QuoteAssemblyFormulaVariable> QuoteAssemblyFormulaVariables { get; set; }
    }
}
