//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationOperationRelation
    {
        public int OperationOperationRelationPK { get; set; }
        public Nullable<int> OperationFromFK { get; set; }
        public Nullable<int> OperationToFK { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual Operation Operation1 { get; set; }
    }
}
