//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderReceivingLine
    {
        public PurchaseOrderReceivingLine()
        {
            this.PurchaseOrderReceivingLineRequirements = new HashSet<PurchaseOrderReceivingLineRequirement>();
            this.QualityControls = new HashSet<QualityControl>();
        }
    
        public int PurchaseOrderReceivingLinePK { get; set; }
        public Nullable<int> PurchaseOrderReceivingFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> UnitOfMeasureSetFK { get; set; }
        public Nullable<int> GeneralLedgerAccountFK { get; set; }
        public Nullable<int> InspectorFK { get; set; }
        public Nullable<int> PurchaseOrderLineFK { get; set; }
        public Nullable<int> PurchaseOrderReceivingLineStatusFK { get; set; }
        public Nullable<int> PurchaseOrderNumber { get; set; }
        public Nullable<int> ItemInventoryLocationFK { get; set; }
        public Nullable<int> LineReferenceNumber { get; set; }
        public Nullable<bool> CertificationsRequired { get; set; }
        public Nullable<bool> GotCertificate { get; set; }
        public Nullable<bool> Inspected { get; set; }
        public bool LotPrice { get; set; }
        public Nullable<bool> MakeFromItem { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<bool> PurchaseToJob { get; set; }
        public Nullable<bool> Rejected { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public Nullable<bool> PopupNotifyComment { get; set; }
        public Nullable<bool> RequiresInspection { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> InspectedDate { get; set; }
        public string Revision { get; set; }
        public string Description { get; set; }
        public string LotNumber { get; set; }
        public string LocationDescription { get; set; }
        public string PartNumber { get; set; }
        public string SerialNumber { get; set; }
        public string VendorPartNumber { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<decimal> QuantityInspected { get; set; }
        public Nullable<decimal> QuantityNotAccepted { get; set; }
        public Nullable<decimal> StockWidth { get; set; }
        public Nullable<decimal> StockLength { get; set; }
        public Nullable<decimal> VendorUnit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QuantityOrdered { get; set; }
        public Nullable<decimal> ComponentCost { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Minimum { get; set; }
        public Nullable<decimal> SalesTax1Amount { get; set; }
        public Nullable<decimal> SalesTax2Amount { get; set; }
        public Nullable<decimal> SalesTax3Amount { get; set; }
        public Nullable<decimal> SalesTax4Amount { get; set; }
        public Nullable<decimal> ExtendedAmount { get; set; }
        public Nullable<decimal> ForeignCurrencyPrice { get; set; }
        public Nullable<decimal> ForeignCurrencyMiscellaneousAmount1 { get; set; }
        public Nullable<decimal> ForeignCurrencyMiscellaneousAmount2 { get; set; }
        public Nullable<decimal> ForeignCurrencyMiscellaneousAmount3 { get; set; }
        public Nullable<decimal> ForeignCurrencyTotalMiscellaneousAmount { get; set; }
        public Nullable<decimal> ForeignCurrencySalesTax1Amount { get; set; }
        public Nullable<decimal> ForeignCurrencySalesTax2Amount { get; set; }
        public Nullable<decimal> ForeignCurrencySalesTax3Amount { get; set; }
        public Nullable<decimal> ForeignCurrencySalesTax4Amount { get; set; }
        public Nullable<decimal> ForeignCurrencyExtendedAmount { get; set; }
        public Nullable<decimal> ExtendedAmountConfirmed { get; set; }
        public Nullable<decimal> LandedCost { get; set; }
        public string InspectComment { get; set; }
        public string RejectComment { get; set; }
        public string Comment { get; set; }
        public string NotifyComment { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<bool> CustomCheckBox1 { get; set; }
        public Nullable<bool> CustomCheckBox2 { get; set; }
        public Nullable<bool> CustomCheckBox3 { get; set; }
        public string SalesTax1Name { get; set; }
        public Nullable<decimal> SalesTax1Rate { get; set; }
        public string SalesTaxType1Description { get; set; }
        public string SalesTax2Name { get; set; }
        public Nullable<decimal> SalesTax2Rate { get; set; }
        public string SalesTaxType2Description { get; set; }
        public string SalesTax3Name { get; set; }
        public Nullable<decimal> SalesTax3Rate { get; set; }
        public string SalesTaxType3Description { get; set; }
        public string SalesTax4Name { get; set; }
        public Nullable<decimal> SalesTax4Rate { get; set; }
        public string SalesTaxType4Description { get; set; }
        public Nullable<decimal> PartWidth { get; set; }
        public Nullable<decimal> PartLength { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<int> ManufacturerFK { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<decimal> WeightPerPiece { get; set; }
        public Nullable<decimal> QuantityInvoiced { get; set; }
        public string Memo { get; set; }
    
        public virtual GeneralLedgerAccount GeneralLedgerAccount { get; set; }
        public virtual Item Item { get; set; }
        public virtual Party Party { get; set; }
        public virtual PurchaseOrderLine PurchaseOrderLine { get; set; }
        public virtual PurchaseOrderReceiving PurchaseOrderReceiving { get; set; }
        public virtual User User { get; set; }
        public virtual PurchaseOrderReceivingLineStatu PurchaseOrderReceivingLineStatu { get; set; }
        public virtual UnitOfMeasureSet UnitOfMeasureSet { get; set; }
        public virtual ICollection<PurchaseOrderReceivingLineRequirement> PurchaseOrderReceivingLineRequirements { get; set; }
        public virtual ICollection<QualityControl> QualityControls { get; set; }
    }
}
