//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderRequest
    {
        public PurchaseOrderRequest()
        {
            this.TaskActivities = new HashSet<TaskActivity>();
        }
    
        public int PurchaseOrderRequestPK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> ApprovedByFK { get; set; }
        public Nullable<int> RequestedByFK { get; set; }
        public Nullable<int> StatusFK { get; set; }
        public Nullable<int> PurchaseOrderNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<System.DateTime> DueByDate { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<decimal> QuantityRequested { get; set; }
        public Nullable<decimal> QuantityApproved { get; set; }
        public string ReasonNeed { get; set; }
        public string Comment { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<bool> RequiresApproval { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> RequestDeniedDate { get; set; }
        public string CustomDescription { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> BuyerAssignedFK { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual PurchaseOrderRequestStatu PurchaseOrderRequestStatu { get; set; }
        public virtual ICollection<TaskActivity> TaskActivities { get; set; }
    }
}
