//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityControlContainmentAction
    {
        public int QualityControlContainmentActionPK { get; set; }
        public Nullable<int> QualityControlFK { get; set; }
        public Nullable<int> TaskActivityFK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<bool> Assign { get; set; }
        public Nullable<bool> Completed { get; set; }
        public string Description { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual QualityControl QualityControl { get; set; }
        public virtual TaskActivity TaskActivity { get; set; }
        public virtual User User { get; set; }
    }
}
