//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteAssemblyFormulaVariable
    {
        public int QuoteAssemblyFormulaVariablePK { get; set; }
        public Nullable<int> QuoteAssemblyFK { get; set; }
        public Nullable<int> OperationFormulaVariableFK { get; set; }
        public Nullable<int> VariableLookupTableFK { get; set; }
        public Nullable<decimal> VariableLookupValue { get; set; }
        public Nullable<decimal> VariableValue { get; set; }
        public Nullable<bool> FormulaType { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    
        public virtual LookupTable LookupTable { get; set; }
        public virtual OperationFormulaVariable OperationFormulaVariable { get; set; }
        public virtual QuoteAssembly QuoteAssembly { get; set; }
    }
}
