//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteAssembly
    {
        public QuoteAssembly()
        {
            this.QuoteAssembly1 = new HashSet<QuoteAssembly>();
            this.QuoteAssemblyCutAnalyzers = new HashSet<QuoteAssemblyCutAnalyzer>();
            this.QuoteAssemblyFormulaVariables = new HashSet<QuoteAssemblyFormulaVariable>();
            this.QuoteAssemblyMachines = new HashSet<QuoteAssemblyMachine>();
        }
    
        public int QuoteAssemblyPK { get; set; }
        public Nullable<int> QuoteFK { get; set; }
        public Nullable<int> ParentQuoteAssemblyFK { get; set; }
        public Nullable<int> ParentQuoteFK { get; set; }
        public Nullable<int> OperationFK { get; set; }
        public Nullable<int> SetupFormulaFK { get; set; }
        public Nullable<int> RunFormulaFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> PartyFK { get; set; }
        public Nullable<int> ItemQuoteFK { get; set; }
        public Nullable<int> UnitOfMeasureSetFK { get; set; }
        public Nullable<int> CalculationTypeFK { get; set; }
        public Nullable<int> RequestForQuoteLineFK { get; set; }
        public Nullable<bool> Tool { get; set; }
        public Nullable<bool> StopSequence { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<decimal> BatchSize { get; set; }
        public Nullable<decimal> SetupTime { get; set; }
        public Nullable<decimal> SetupLaborCost { get; set; }
        public Nullable<decimal> SetupEquipmentCharge { get; set; }
        public Nullable<decimal> SetupCost { get; set; }
        public Nullable<decimal> SetupPrice { get; set; }
        public Nullable<decimal> SetupOperationProfitRate { get; set; }
        public Nullable<decimal> SetupOperationOverHeadRate { get; set; }
        public Nullable<int> SetupEmployees { get; set; }
        public Nullable<decimal> SetupEmployeeRate { get; set; }
        public Nullable<decimal> SetupEmployeeOverHeadRate { get; set; }
        public Nullable<decimal> SetupMarkupPercentage { get; set; }
        public string SetupFormula { get; set; }
        public Nullable<decimal> RunTime { get; set; }
        public Nullable<decimal> RunLaborCost { get; set; }
        public Nullable<decimal> RunEquipmentCharge { get; set; }
        public Nullable<decimal> RunCost { get; set; }
        public Nullable<decimal> RunPrice { get; set; }
        public Nullable<decimal> RunOperationProfitRate { get; set; }
        public Nullable<decimal> RunOperationOverHeadRate { get; set; }
        public Nullable<int> RunEmployees { get; set; }
        public Nullable<decimal> RunEmployeeRate { get; set; }
        public Nullable<decimal> RunEmployeeOverHeadRate { get; set; }
        public Nullable<decimal> RunMarkupPercentage { get; set; }
        public string RunFormula { get; set; }
        public Nullable<bool> UnattendedOperation { get; set; }
        public Nullable<decimal> UnattendedPercentage { get; set; }
        public Nullable<bool> DoNotUseDeliverySchedule { get; set; }
        public Nullable<decimal> VendorUnit { get; set; }
        public string DrawingNumber { get; set; }
        public string MarkNumber { get; set; }
        public Nullable<bool> GrainDirection { get; set; }
        public Nullable<decimal> Thickness { get; set; }
        public Nullable<decimal> Tolerance { get; set; }
        public Nullable<decimal> WeightFactor { get; set; }
        public Nullable<decimal> StockWidth { get; set; }
        public Nullable<decimal> StockLength { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public Nullable<decimal> SetupCharge { get; set; }
        public Nullable<decimal> MinimumCharge { get; set; }
        public Nullable<decimal> PartWidth { get; set; }
        public Nullable<decimal> PartLength { get; set; }
        public Nullable<decimal> PartsRequired { get; set; }
        public Nullable<decimal> QuantityRequired { get; set; }
        public Nullable<decimal> QuantityPerInverse { get; set; }
        public Nullable<decimal> EstimatedAmount { get; set; }
        public Nullable<decimal> SquareInchesOrLbsEstimate { get; set; }
        public Nullable<decimal> MinimumPiecePrice { get; set; }
        public Nullable<decimal> BlankWidth { get; set; }
        public Nullable<decimal> BlankLength { get; set; }
        public Nullable<decimal> PartsPerBlank { get; set; }
        public Nullable<decimal> PartsPerBlankScrapPercentage { get; set; }
        public Nullable<decimal> SafetyStockWidth { get; set; }
        public Nullable<decimal> SafetyStockLength { get; set; }
        public Nullable<decimal> ShippingCharge { get; set; }
        public Nullable<int> DaysOut { get; set; }
        public Nullable<decimal> OveragePercentage { get; set; }
        public Nullable<bool> AgainstGrain { get; set; }
        public Nullable<bool> DoubleSided { get; set; }
        public Nullable<bool> CertificationsRequired { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> NonAmortizedItem { get; set; }
        public Nullable<decimal> Quantity1 { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> MarkupPercentage1 { get; set; }
        public Nullable<decimal> Quantity2 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> MarkupPercentage2 { get; set; }
        public Nullable<decimal> Quantity3 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<decimal> MarkupPercentage3 { get; set; }
        public Nullable<decimal> Quantity4 { get; set; }
        public Nullable<decimal> Price4 { get; set; }
        public Nullable<decimal> MarkupPercentage4 { get; set; }
        public Nullable<decimal> Quantity5 { get; set; }
        public Nullable<decimal> Price5 { get; set; }
        public Nullable<decimal> MarkupPercentage5 { get; set; }
        public Nullable<decimal> Quantity6 { get; set; }
        public Nullable<decimal> Price6 { get; set; }
        public Nullable<decimal> MarkupPercentage6 { get; set; }
        public Nullable<decimal> Quantity7 { get; set; }
        public Nullable<decimal> Price7 { get; set; }
        public Nullable<decimal> MarkupPercentage7 { get; set; }
        public Nullable<decimal> Quantity8 { get; set; }
        public Nullable<decimal> Price8 { get; set; }
        public Nullable<decimal> MarkupPercentage8 { get; set; }
        public Nullable<System.DateTime> GoodUntil { get; set; }
        public Nullable<decimal> PieceWeight { get; set; }
        public Nullable<decimal> CustomPieceWeight { get; set; }
        public Nullable<bool> Pull { get; set; }
        public Nullable<int> ProductItem { get; set; }
        public Nullable<int> ProductOrder { get; set; }
        public Nullable<decimal> PieceCost { get; set; }
        public Nullable<decimal> PiecePrice { get; set; }
        public Nullable<int> StockPieces { get; set; }
        public Nullable<decimal> StockPiecesScrapPercentage { get; set; }
        public Nullable<bool> NotIncludeInPiecePrice { get; set; }
        public Nullable<bool> Lock { get; set; }
        public Nullable<decimal> FabricationQuantity1 { get; set; }
        public Nullable<decimal> FabricationQuantity2 { get; set; }
        public Nullable<decimal> FabricationQuantity3 { get; set; }
        public Nullable<decimal> FabricationQuantity4 { get; set; }
        public Nullable<decimal> FabricationQuantity5 { get; set; }
        public Nullable<decimal> ConcurrentSetups1 { get; set; }
        public Nullable<decimal> ConcurrentSetups2 { get; set; }
        public Nullable<decimal> ConcurrentSetups3 { get; set; }
        public Nullable<decimal> ConcurrentSetups4 { get; set; }
        public Nullable<decimal> ConcurrentSetups5 { get; set; }
        public string CountryOfOrigin { get; set; }
        public string OverheadRateTypeCode { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> QuoteAssemblySeqNumberFK { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> ScrapRebate { get; set; }
    
        public virtual CalculationType CalculationType { get; set; }
        public virtual Item Item { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual OperationFormula OperationFormula { get; set; }
        public virtual OperationFormula OperationFormula1 { get; set; }
        public virtual Party Party { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual Quote Quote1 { get; set; }
        public virtual Quote Quote2 { get; set; }
        public virtual ICollection<QuoteAssembly> QuoteAssembly1 { get; set; }
        public virtual QuoteAssembly QuoteAssembly2 { get; set; }
        public virtual RequestForQuoteLine RequestForQuoteLine { get; set; }
        public virtual UnitOfMeasureSet UnitOfMeasureSet { get; set; }
        public virtual ICollection<QuoteAssemblyCutAnalyzer> QuoteAssemblyCutAnalyzers { get; set; }
        public virtual ICollection<QuoteAssemblyFormulaVariable> QuoteAssemblyFormulaVariables { get; set; }
        public virtual ICollection<QuoteAssemblyMachine> QuoteAssemblyMachines { get; set; }
    }
}
