//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteAssemblyCutAnalyzer
    {
        public int QuoteAssemblyCutAnalyzerPK { get; set; }
        public Nullable<int> QuoteAssemblyFK { get; set; }
        public Nullable<decimal> Quantity1 { get; set; }
        public Nullable<decimal> ObroundLength1 { get; set; }
        public Nullable<decimal> ObroundWidth1 { get; set; }
        public Nullable<decimal> RectangleLength1 { get; set; }
        public Nullable<decimal> CutLength1 { get; set; }
        public Nullable<decimal> Quantity2 { get; set; }
        public Nullable<decimal> ObroundLength2 { get; set; }
        public Nullable<decimal> ObroundWidth2 { get; set; }
        public Nullable<decimal> RectangleLength2 { get; set; }
        public Nullable<decimal> CutLength2 { get; set; }
        public Nullable<decimal> Quantity3 { get; set; }
        public Nullable<decimal> ObroundLength3 { get; set; }
        public Nullable<decimal> ObroundWidth3 { get; set; }
        public Nullable<decimal> RectangleLength3 { get; set; }
        public Nullable<decimal> CutLength3 { get; set; }
        public Nullable<decimal> Quantity4 { get; set; }
        public Nullable<decimal> ObroundLength4 { get; set; }
        public Nullable<decimal> ObroundWidth4 { get; set; }
        public Nullable<decimal> RectangleLength4 { get; set; }
        public Nullable<decimal> CutLength4 { get; set; }
        public Nullable<decimal> Quantity5 { get; set; }
        public Nullable<decimal> ObroundLength5 { get; set; }
        public Nullable<decimal> ObroundWidth5 { get; set; }
        public Nullable<decimal> RectangleLength5 { get; set; }
        public Nullable<decimal> CutLength5 { get; set; }
        public Nullable<decimal> Quantity6 { get; set; }
        public Nullable<decimal> ObroundLength6 { get; set; }
        public Nullable<decimal> ObroundWidth6 { get; set; }
        public Nullable<decimal> RectangleLength6 { get; set; }
        public Nullable<decimal> CutLength6 { get; set; }
        public Nullable<decimal> Quantity7 { get; set; }
        public Nullable<decimal> ObroundLength7 { get; set; }
        public Nullable<decimal> ObroundWidth7 { get; set; }
        public Nullable<decimal> RectangleLength7 { get; set; }
        public Nullable<decimal> CutLength7 { get; set; }
        public Nullable<decimal> Quantity8 { get; set; }
        public Nullable<decimal> ObroundLength8 { get; set; }
        public Nullable<decimal> ObroundWidth8 { get; set; }
        public Nullable<decimal> RectangleLength8 { get; set; }
        public Nullable<decimal> CutLength8 { get; set; }
        public Nullable<decimal> Quantity9 { get; set; }
        public Nullable<decimal> ObroundLength9 { get; set; }
        public Nullable<decimal> ObroundWidth9 { get; set; }
        public Nullable<decimal> RectangleLength9 { get; set; }
        public Nullable<decimal> CutLength9 { get; set; }
        public Nullable<decimal> Quantity10 { get; set; }
        public Nullable<decimal> ObroundLength10 { get; set; }
        public Nullable<decimal> ObroundWidth10 { get; set; }
        public Nullable<decimal> RectangleLength10 { get; set; }
        public Nullable<decimal> CutLength10 { get; set; }
        public Nullable<decimal> Quantity11 { get; set; }
        public Nullable<decimal> ObroundLength11 { get; set; }
        public Nullable<decimal> ObroundWidth11 { get; set; }
        public Nullable<decimal> RectangleLength11 { get; set; }
        public Nullable<decimal> CutLength11 { get; set; }
        public Nullable<decimal> Quantity12 { get; set; }
        public Nullable<decimal> ObroundLength12 { get; set; }
        public Nullable<decimal> ObroundWidth12 { get; set; }
        public Nullable<decimal> RectangleLength12 { get; set; }
        public Nullable<decimal> CutLength12 { get; set; }
        public Nullable<decimal> Quantity13 { get; set; }
        public Nullable<decimal> ObroundLength13 { get; set; }
        public Nullable<decimal> ObroundWidth13 { get; set; }
        public Nullable<decimal> RectangleLength13 { get; set; }
        public Nullable<decimal> CutLength13 { get; set; }
        public Nullable<decimal> Quantity14 { get; set; }
        public Nullable<decimal> ObroundLength14 { get; set; }
        public Nullable<decimal> ObroundWidth14 { get; set; }
        public Nullable<decimal> RectangleLength14 { get; set; }
        public Nullable<decimal> CutLength14 { get; set; }
        public Nullable<decimal> Quantity15 { get; set; }
        public Nullable<decimal> ObroundLength15 { get; set; }
        public Nullable<decimal> ObroundWidth15 { get; set; }
        public Nullable<decimal> RectangleLength15 { get; set; }
        public Nullable<decimal> CutLength15 { get; set; }
        public Nullable<decimal> TotalLengthCut { get; set; }
        public Nullable<decimal> TotalPierces { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual QuoteAssembly QuoteAssembly { get; set; }
    }
}
