//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteQuantity
    {
        public int QuoteQuantityPK { get; set; }
        public Nullable<int> QuoteFK { get; set; }
        public Nullable<decimal> MarkupPercentage { get; set; }
        public Nullable<decimal> MarkupPercentageMaterial { get; set; }
        public Nullable<decimal> MarkupPercentageHardware { get; set; }
        public Nullable<decimal> MarkupPercentageOutsideProcessing { get; set; }
        public Nullable<decimal> MarkupPercentageLabor { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Delivery { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
        public Nullable<decimal> EstimatedHours { get; set; }
        public Nullable<decimal> SetupTime { get; set; }
        public Nullable<decimal> SetupLaborCost { get; set; }
        public Nullable<decimal> SetupEquipmentCharge { get; set; }
        public Nullable<decimal> SetupCost { get; set; }
        public Nullable<decimal> SetupPrice { get; set; }
        public Nullable<decimal> RunTime { get; set; }
        public Nullable<decimal> RunLaborCost { get; set; }
        public Nullable<decimal> RunEquipmentCharge { get; set; }
        public Nullable<decimal> RunCost { get; set; }
        public Nullable<decimal> RunPrice { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public Nullable<decimal> MaterialPrice { get; set; }
        public Nullable<decimal> HardwareCost { get; set; }
        public Nullable<decimal> HardwarePrice { get; set; }
        public Nullable<decimal> StandardCost { get; set; }
        public Nullable<decimal> StandardPrice { get; set; }
        public Nullable<decimal> MiscellaneousCost { get; set; }
        public Nullable<decimal> KitCost { get; set; }
        public Nullable<decimal> KitPrice { get; set; }
        public Nullable<decimal> MiscellaneousPrice { get; set; }
        public Nullable<decimal> OutsideProcessingCost { get; set; }
        public Nullable<decimal> OutsideProcessingPrice { get; set; }
        public Nullable<decimal> ShippingCharge { get; set; }
        public Nullable<decimal> CutQuantity { get; set; }
        public Nullable<decimal> ToolingCharge { get; set; }
        public Nullable<bool> PrimaryPrice { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Quote Quote { get; set; }
    }
}
