//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reconciliation
    {
        public Reconciliation()
        {
            this.ReconciliationLines = new HashSet<ReconciliationLine>();
        }
    
        public int ReconciliationPK { get; set; }
        public Nullable<int> ReconciliationAccountFK { get; set; }
        public Nullable<int> ServiceChargeAccountFK { get; set; }
        public Nullable<int> InterestEarnedAccountFK { get; set; }
        public Nullable<int> ReconciliationStatusFK { get; set; }
        public Nullable<int> ReconciliationNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
        public Nullable<decimal> BeginningBalance { get; set; }
        public Nullable<decimal> EndingBalance { get; set; }
        public Nullable<decimal> TotalCustomerPaymentAmount { get; set; }
        public Nullable<decimal> TotalBillPaymentAmount { get; set; }
        public Nullable<decimal> ReconcilationAccountBalanceTotal { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
        public Nullable<System.DateTime> ServiceChargeDate { get; set; }
        public Nullable<decimal> InterestEarned { get; set; }
        public Nullable<System.DateTime> InterestEarnedDate { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual GeneralLedgerAccount GeneralLedgerAccount { get; set; }
        public virtual GeneralLedgerAccount GeneralLedgerAccount1 { get; set; }
        public virtual GeneralLedgerAccount GeneralLedgerAccount2 { get; set; }
        public virtual ReconciliationStatu ReconciliationStatu { get; set; }
        public virtual ICollection<ReconciliationLine> ReconciliationLines { get; set; }
    }
}
