//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDivision
    {
        public ReportDivision()
        {
            this.ReportDivisionUsers = new HashSet<ReportDivisionUser>();
        }
    
        public int ReportDivisionPK { get; set; }
        public Nullable<int> ReportFK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public string Description { get; set; }
        public string Revision { get; set; }
        public byte[] ReportContent { get; set; }
        public Nullable<bool> DirectEmail { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<bool> Master { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> ShowToAll { get; set; }
        public Nullable<bool> DefaultReport { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> QuickViewFK { get; set; }
        public Nullable<bool> Printer { get; set; }
        public string EmailFileName { get; set; }
        public byte[] SubreportContent { get; set; }
        public string DefaultPrinter { get; set; }
        public string PaperSource { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual QuickView QuickView { get; set; }
        public virtual Report Report { get; set; }
        public virtual ICollection<ReportDivisionUser> ReportDivisionUsers { get; set; }
    }
}
