//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderStatu
    {
        public SalesOrderStatu()
        {
            this.SalesOrders = new HashSet<SalesOrder>();
            this.SalesOrderLines = new HashSet<SalesOrderLine>();
            this.SalesOrderLineItemInventoryLocations = new HashSet<SalesOrderLineItemInventoryLocation>();
        }
    
        public int SalesOrderStatusPK { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
        public virtual ICollection<SalesOrderLine> SalesOrderLines { get; set; }
        public virtual ICollection<SalesOrderLineItemInventoryLocation> SalesOrderLineItemInventoryLocations { get; set; }
        public virtual SalesOrderStatu SalesOrderStatus1 { get; set; }
        public virtual SalesOrderStatu SalesOrderStatu1 { get; set; }
    }
}
