//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderLineItemInventoryLocation
    {
        public int SalesOrderLineItemInventoryLocationPK { get; set; }
        public Nullable<int> SalesOrderLineFK { get; set; }
        public Nullable<int> ItemInventoryLocationFK { get; set; }
        public Nullable<int> SalesOrderStatusFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ItemInventoryLocation ItemInventoryLocation { get; set; }
        public virtual SalesOrderLine SalesOrderLine { get; set; }
        public virtual SalesOrderStatu SalesOrderStatu { get; set; }
    }
}
