//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public SalesOrder()
        {
            this.BusinessProcessResults = new HashSet<BusinessProcessResult>();
            this.Documents = new HashSet<Document>();
            this.MRPDetails = new HashSet<MRPDetail>();
            this.PickLists = new HashSet<PickList>();
            this.SalesOrderCorrespondances = new HashSet<SalesOrderCorrespondance>();
            this.SalesOrderLines = new HashSet<SalesOrderLine>();
            this.SalesOrderSalespersons = new HashSet<SalesOrderSalesperson>();
            this.TaskActivities = new HashSet<TaskActivity>();
            this.TaskJournals = new HashSet<TaskJournal>();
            this.WorkOrderJobs = new HashSet<WorkOrderJob>();
        }
    
        public int SalesOrderPK { get; set; }
        public Nullable<int> BuyerFK { get; set; }
        public Nullable<int> BillingAddressFK { get; set; }
        public Nullable<int> CurrencyCodeFK { get; set; }
        public Nullable<int> CustomerFK { get; set; }
        public Nullable<int> DiscountFK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public Nullable<int> ShippingAddressFK { get; set; }
        public Nullable<int> ShipViaFK { get; set; }
        public Nullable<int> SalesOrderStatusFK { get; set; }
        public Nullable<int> ProjectFK { get; set; }
        public Nullable<int> TermFK { get; set; }
        public Nullable<int> ChangeNo { get; set; }
        public Nullable<int> SalesOrderNumber { get; set; }
        public Nullable<int> ExpediterNumber { get; set; }
        public Nullable<bool> ChargeFreight { get; set; }
        public Nullable<bool> CodPrepayedFlag { get; set; }
        public Nullable<bool> EdiOrder { get; set; }
        public Nullable<bool> MIEExchangeOrder { get; set; }
        public Nullable<bool> ReceivedPurchaseOrder { get; set; }
        public Nullable<bool> RMA { get; set; }
        public Nullable<bool> PopupNotifyComment { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<System.DateTime> MaterialsDateRequest { get; set; }
        public Nullable<System.DateTime> MaterialDateReceived { get; set; }
        public string Delivery { get; set; }
        public string ExternalReferenceNumber { get; set; }
        public string PrepaidOrCollection { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string RequestForQuoteNumber { get; set; }
        public string UserDefinedPO { get; set; }
        public string FreightOnBoard { get; set; }
        public Nullable<decimal> FreightPerPound { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public Nullable<decimal> DepositAmountApplied { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> FreightCharge { get; set; }
        public string ShippingNotes { get; set; }
        public string ManufacturingNotes { get; set; }
        public string Comment { get; set; }
        public string NotifyComment { get; set; }
        public string BillingAddressName { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingAddressAlt { get; set; }
        public string BillingAddressCity { get; set; }
        public string BillingAddressZipCode { get; set; }
        public string ShippingAddressName { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingAddressAlt { get; set; }
        public string ShippingAddressCity { get; set; }
        public string ShippingAddressZipCode { get; set; }
        public string SalesTax1Name { get; set; }
        public Nullable<decimal> SalesTax1Rate { get; set; }
        public string SalesTaxType1Description { get; set; }
        public string SalesTax2Name { get; set; }
        public Nullable<decimal> SalesTax2Rate { get; set; }
        public string SalesTaxType2Description { get; set; }
        public string SalesTax3Name { get; set; }
        public Nullable<decimal> SalesTax3Rate { get; set; }
        public string SalesTaxType3Description { get; set; }
        public string SalesTax4Name { get; set; }
        public Nullable<decimal> SalesTax4Rate { get; set; }
        public string SalesTaxType4Description { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> FreightCodeFK { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ICollection<BusinessProcessResult> BusinessProcessResults { get; set; }
        public virtual CurrencyCode CurrencyCode { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual Division Division { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual FreightCode FreightCode { get; set; }
        public virtual ICollection<MRPDetail> MRPDetails { get; set; }
        public virtual Party Party { get; set; }
        public virtual Party Party1 { get; set; }
        public virtual ICollection<PickList> PickLists { get; set; }
        public virtual Project Project { get; set; }
        public virtual SalesOrderStatu SalesOrderStatu { get; set; }
        public virtual ShipVia ShipVia { get; set; }
        public virtual Term Term { get; set; }
        public virtual ICollection<SalesOrderCorrespondance> SalesOrderCorrespondances { get; set; }
        public virtual ICollection<SalesOrderLine> SalesOrderLines { get; set; }
        public virtual ICollection<SalesOrderSalesperson> SalesOrderSalespersons { get; set; }
        public virtual ICollection<TaskActivity> TaskActivities { get; set; }
        public virtual ICollection<TaskJournal> TaskJournals { get; set; }
        public virtual ICollection<WorkOrderJob> WorkOrderJobs { get; set; }
    }
}
