//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleResourceException
    {
        public int ScheduleResourceExceptionPK { get; set; }
        public int ScheduleResourceFK { get; set; }
        public string Description { get; set; }
        public System.DateTime ExceptionDate { get; set; }
        public int ExceptionType { get; set; }
        public int DurationMinute { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ScheduleResource ScheduleResource { get; set; }
    }
}
