//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetail
    {
        public ScheduleDetail()
        {
            this.ScheduleDetailEmployees = new HashSet<ScheduleDetailEmployee>();
            this.ScheduleDetailMaterials = new HashSet<ScheduleDetailMaterial>();
            this.ScheduleDetailPredecessors = new HashSet<ScheduleDetailPredecessor>();
            this.ScheduleDetailPredecessors1 = new HashSet<ScheduleDetailPredecessor>();
        }
    
        public int ScheduleDetailPK { get; set; }
        public Nullable<int> ScheduleFK { get; set; }
        public Nullable<int> MachineFK { get; set; }
        public Nullable<int> WorkOrderReleaseFK { get; set; }
        public Nullable<int> WorkOrderAssemblyFK { get; set; }
        public Nullable<int> EmployeeFK { get; set; }
        public string Description { get; set; }
        public System.DateTime StartTime { get; set; }
        public int EffortMinutes { get; set; }
        public int CompletedEffortMinutes { get; set; }
        public string Customer { get; set; }
        public string PartNumber { get; set; }
        public string WorkOrderNumber { get; set; }
        public string RouterNumber { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> SubDueDate { get; set; }
        public Nullable<decimal> EstimatedHours { get; set; }
        public string MaterialDescription { get; set; }
        public string HardwareDescription { get; set; }
        public string OutsideProcessingDescription { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<decimal> StockWidth { get; set; }
        public Nullable<decimal> StockLength { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> QuantityToProduce { get; set; }
        public Nullable<System.DateTime> TargetStartDate { get; set; }
        public Nullable<decimal> Thickness { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual User User { get; set; }
        public virtual WorkOrderAssembly WorkOrderAssembly { get; set; }
        public virtual WorkOrderRelease WorkOrderRelease { get; set; }
        public virtual ICollection<ScheduleDetailEmployee> ScheduleDetailEmployees { get; set; }
        public virtual ICollection<ScheduleDetailMaterial> ScheduleDetailMaterials { get; set; }
        public virtual ICollection<ScheduleDetailPredecessor> ScheduleDetailPredecessors { get; set; }
        public virtual ICollection<ScheduleDetailPredecessor> ScheduleDetailPredecessors1 { get; set; }
    }
}
