//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatementExplosion
    {
        public int StatementExplosionPK { get; set; }
        public Nullable<int> StatementFK { get; set; }
        public Nullable<int> StatementDetailFK { get; set; }
        public Nullable<int> GeneralLedgerAcccountFK { get; set; }
        public Nullable<int> StatementDetailNameFK { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual GeneralLedgerAccount GeneralLedgerAccount { get; set; }
        public virtual Statement Statement { get; set; }
        public virtual StatementDetail StatementDetail { get; set; }
        public virtual StatementDetail StatementDetail1 { get; set; }
    }
}
