//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskWorkFlowTemplateDetail
    {
        public int TaskWorkFlowTemplateDetailPK { get; set; }
        public Nullable<int> TaskWorkFlowTemplateFK { get; set; }
        public Nullable<int> AssignedToFK { get; set; }
        public int OrderIndex { get; set; }
        public Nullable<int> Days { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> EmailAssignedTo { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual TaskWorkFlowTemplate TaskWorkFlowTemplate { get; set; }
        public virtual User User { get; set; }
    }
}
