//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccrualLog
    {
        public int UserAccrualLogPK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> TimeCardFK { get; set; }
        public Nullable<int> UserAccrualFK { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public decimal EditHoursAmount { get; set; }
        public Nullable<int> AdjustmentType { get; set; }
        public string Comment { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual TimeCard TimeCard { get; set; }
        public virtual User User { get; set; }
        public virtual UserAccrual UserAccrual { get; set; }
    }
}
