//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLog
    {
        public int ViewLogPK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> ModuleFK { get; set; }
        public string ViewId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ViewTime { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
    }
}
