//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderNestStatu
    {
        public WorkOrderNestStatu()
        {
            this.WorkOrderNests = new HashSet<WorkOrderNest>();
            this.WorkOrderNestJobs = new HashSet<WorkOrderNestJob>();
            this.WorkOrderPrograms = new HashSet<WorkOrderProgram>();
            this.WorkOrderProgramLayouts = new HashSet<WorkOrderProgramLayout>();
        }
    
        public int WorkOrderNestStatusPK { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<WorkOrderNest> WorkOrderNests { get; set; }
        public virtual ICollection<WorkOrderNestJob> WorkOrderNestJobs { get; set; }
        public virtual ICollection<WorkOrderProgram> WorkOrderPrograms { get; set; }
        public virtual ICollection<WorkOrderProgramLayout> WorkOrderProgramLayouts { get; set; }
    }
}
