//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderTypeOfHour
    {
        public WorkOrderTypeOfHour()
        {
            this.WorkOrderCollections = new HashSet<WorkOrderCollection>();
            this.WorkOrderProgramCollections = new HashSet<WorkOrderProgramCollection>();
        }
    
        public int WorkOrderTypeOfHourPK { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<WorkOrderCollection> WorkOrderCollections { get; set; }
        public virtual ICollection<WorkOrderProgramCollection> WorkOrderProgramCollections { get; set; }
    }
}
