//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderProgramLayout
    {
        public WorkOrderProgramLayout()
        {
            this.WorkOrderProgramLayoutWorkOrders = new HashSet<WorkOrderProgramLayoutWorkOrder>();
        }
    
        public int WorkOrderProgramLayoutPK { get; set; }
        public Nullable<int> WorkOrderProgramFK { get; set; }
        public Nullable<int> RepeatQuantity { get; set; }
        public Nullable<decimal> LayoutRuntime { get; set; }
        public Nullable<decimal> LayoutMaterialUsage { get; set; }
        public Nullable<decimal> StockWidth { get; set; }
        public Nullable<decimal> StockLength { get; set; }
        public Nullable<decimal> Thickness { get; set; }
        public string Material { get; set; }
        public string NCCodeFilename { get; set; }
        public string LayoutFilename { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> WorkOrderNestStatusFK { get; set; }
        public Nullable<int> RepeatQuantityCompleted { get; set; }
        public Nullable<int> ActualPartQuantityProduced { get; set; }
        public Nullable<int> WorkOrderProgramLayoutStatusFK { get; set; }
    
        public virtual WorkOrderNestStatu WorkOrderNestStatu { get; set; }
        public virtual WorkOrderProgram WorkOrderProgram { get; set; }
        public virtual WorkOrderProgramLayoutStatu WorkOrderProgramLayoutStatu { get; set; }
        public virtual ICollection<WorkOrderProgramLayoutWorkOrder> WorkOrderProgramLayoutWorkOrders { get; set; }
    }
}
