//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIInspection.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public WorkOrder()
        {
            this.BusinessProcessResults = new HashSet<BusinessProcessResult>();
            this.Documents = new HashSet<Document>();
            this.MRPDetails = new HashSet<MRPDetail>();
            this.PickLists = new HashSet<PickList>();
            this.QualityControls = new HashSet<QualityControl>();
            this.TaskActivities = new HashSet<TaskActivity>();
            this.TaskJournals = new HashSet<TaskJournal>();
            this.WorkOrderAssemblies = new HashSet<WorkOrderAssembly>();
            this.WorkOrderCompletions = new HashSet<WorkOrderCompletion>();
            this.WorkOrderJobs = new HashSet<WorkOrderJob>();
            this.WorkOrderReleases = new HashSet<WorkOrderRelease>();
            this.WorkOrderSplits = new HashSet<WorkOrderSplit>();
        }
    
        public int WorkOrderPK { get; set; }
        public Nullable<int> CustomerFK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> HardwareCertificationFK { get; set; }
        public Nullable<int> MaterialCertificationFK { get; set; }
        public Nullable<int> OutsideProcessingCertificationFK { get; set; }
        public Nullable<int> RouterFK { get; set; }
        public Nullable<int> WorkOrderTotalFK { get; set; }
        public Nullable<int> WorkOrderStatusFK { get; set; }
        public Nullable<int> CellFK { get; set; }
        public Nullable<int> CellNumber { get; set; }
        public Nullable<int> ExpediterNumber { get; set; }
        public Nullable<int> Priority { get; set; }
        public string ExternalReferenceNumber { get; set; }
        public string ItemDescription { get; set; }
        public string PartNumber { get; set; }
        public string Revision { get; set; }
        public string WorkOrderNumber { get; set; }
        public Nullable<decimal> CostingQuantity { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<decimal> MRPQuantity { get; set; }
        public Nullable<decimal> QuantityRequired { get; set; }
        public Nullable<decimal> QuantityFab { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<System.DateTime> CustomerOnDockDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> EstimatedCompletionDate { get; set; }
        public Nullable<System.DateTime> EstimatedStartDate { get; set; }
        public Nullable<System.DateTime> InitialReleaseDate { get; set; }
        public Nullable<System.DateTime> PlannedStartDate { get; set; }
        public Nullable<System.DateTime> ProductionDueDate { get; set; }
        public Nullable<System.DateTime> ProductionStartDate { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public Nullable<System.DateTime> ReleasedToManufacturingDate { get; set; }
        public Nullable<System.DateTime> SchedulingExpectedCompletionDate { get; set; }
        public Nullable<System.DateTime> SchedulingExpectedStartDate { get; set; }
        public Nullable<System.DateTime> SchedulingStartDateOverride { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> WorkOrderCostReviewDate { get; set; }
        public Nullable<bool> CertificationOfPerformanceRequired { get; set; }
        public Nullable<bool> DoNotShowThoseWithFixedSchedules { get; set; }
        public Nullable<bool> DoNotShowThoseSayingDoNotSchedule { get; set; }
        public Nullable<bool> HardwareApprovedSupplierRequired { get; set; }
        public Nullable<bool> MaterialApprovedSupplierRequired { get; set; }
        public Nullable<bool> OutsideProcessingApprovedSupplierRequired { get; set; }
        public Nullable<bool> PopUpNotifyWOCommentsBit { get; set; }
        public Nullable<bool> Printed { get; set; }
        public Nullable<bool> RemoveFromSchedule { get; set; }
        public Nullable<bool> RequiresSource { get; set; }
        public Nullable<bool> Rework { get; set; }
        public Nullable<bool> ScheduleProcessing { get; set; }
        public Nullable<bool> UserDefinedBit1 { get; set; }
        public Nullable<bool> UserDefinedBit2 { get; set; }
        public Nullable<bool> UserDefinedBit3 { get; set; }
        public Nullable<System.DateTime> UserDefinedDate1 { get; set; }
        public Nullable<System.DateTime> UserDefinedDate2 { get; set; }
        public Nullable<System.DateTime> UserDefinedDate3 { get; set; }
        public string UserDefinedText1 { get; set; }
        public string UserDefinedText2 { get; set; }
        public string UserDefinedText3 { get; set; }
        public string ManufacturingNotes { get; set; }
        public string PopUpNotifyWOComments { get; set; }
        public string ReworkNotes { get; set; }
        public string ShippingNotes { get; set; }
        public string WorkOrderComments { get; set; }
        public Nullable<bool> ReleaseProcessing { get; set; }
        public byte[] LastAccess { get; set; }
        public string CustomDescription { get; set; }
        public Nullable<bool> UserDefinedBit4 { get; set; }
        public Nullable<bool> UserDefinedBit5 { get; set; }
        public Nullable<bool> UserDefinedBit6 { get; set; }
        public Nullable<int> OriginalReworkWONumber { get; set; }
        public Nullable<System.DateTime> ScheduledStartDateAPS { get; set; }
        public Nullable<System.DateTime> ScheduledEndDateAPS { get; set; }
        public Nullable<bool> FirstArticleRequired { get; set; }
        public Nullable<bool> ExcludeFromAPSSchedue { get; set; }
        public Nullable<bool> Fair { get; set; }
        public Nullable<bool> KitExploded { get; set; }
        public Nullable<bool> DoNotAllowUnreleaseAfterWORelease { get; set; }
        public Nullable<System.DateTime> AccountingCloseDate { get; set; }
    
        public virtual ICollection<BusinessProcessResult> BusinessProcessResults { get; set; }
        public virtual Cell Cell { get; set; }
        public virtual CertificationType CertificationType { get; set; }
        public virtual CertificationType CertificationType1 { get; set; }
        public virtual CertificationType CertificationType2 { get; set; }
        public virtual Division Division { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<MRPDetail> MRPDetails { get; set; }
        public virtual Party Party { get; set; }
        public virtual ICollection<PickList> PickLists { get; set; }
        public virtual ICollection<QualityControl> QualityControls { get; set; }
        public virtual Router Router { get; set; }
        public virtual ICollection<TaskActivity> TaskActivities { get; set; }
        public virtual ICollection<TaskJournal> TaskJournals { get; set; }
        public virtual WorkOrderStatu WorkOrderStatu { get; set; }
        public virtual WorkOrderTotal WorkOrderTotal { get; set; }
        public virtual ICollection<WorkOrderAssembly> WorkOrderAssemblies { get; set; }
        public virtual ICollection<WorkOrderCompletion> WorkOrderCompletions { get; set; }
        public virtual ICollection<WorkOrderJob> WorkOrderJobs { get; set; }
        public virtual ICollection<WorkOrderRelease> WorkOrderReleases { get; set; }
        public virtual ICollection<WorkOrderSplit> WorkOrderSplits { get; set; }
    }
}
