//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillPaymentCheck
    {
        public BillPaymentCheck()
        {
            this.BillPaymentApplies = new HashSet<BillPaymentApply>();
            this.GeneralLedgerDetails = new HashSet<GeneralLedgerDetail>();
            this.ReconciliationLines = new HashSet<ReconciliationLine>();
        }
    
        public int BillPaymentCheckPK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public Nullable<int> PayFromAccountFK { get; set; }
        public Nullable<int> PartyFK { get; set; }
        public Nullable<int> BillingAddressFK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> BillPaymentCheckStatusFK { get; set; }
        public Nullable<int> CheckNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> VoidCheckDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Memo { get; set; }
        public Nullable<bool> IsCleared { get; set; }
        public byte[] LastAccess { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string AddressAlt { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string AddressName { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<BillPaymentApply> BillPaymentApplies { get; set; }
        public virtual BillPaymentCheckStatu BillPaymentCheckStatu { get; set; }
        public virtual Division Division { get; set; }
        public virtual GeneralLedgerAccount GeneralLedgerAccount { get; set; }
        public virtual Party Party { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<GeneralLedgerDetail> GeneralLedgerDetails { get; set; }
        public virtual ICollection<ReconciliationLine> ReconciliationLines { get; set; }
    }
}
