//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillPaymentCheckStatu
    {
        public BillPaymentCheckStatu()
        {
            this.BillPaymentChecks = new HashSet<BillPaymentCheck>();
        }
    
        public int BillPaymentCheckStatusPK { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<BillPaymentCheck> BillPaymentChecks { get; set; }
    }
}
