//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public Budget()
        {
            this.BudgetAccounts = new HashSet<BudgetAccount>();
        }
    
        public int BudgetPK { get; set; }
        public Nullable<int> FiscalCalendarFK { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual FiscalCalendar FiscalCalendar { get; set; }
        public virtual ICollection<BudgetAccount> BudgetAccounts { get; set; }
    }
}
