//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessProcessTemplate
    {
        public BusinessProcessTemplate()
        {
            this.BusinessProcessTemplateDetails = new HashSet<BusinessProcessTemplateDetail>();
        }
    
        public int BusinessProcessTemplatePK { get; set; }
        public Nullable<int> BusinessProcessFK { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual BusinessProcess BusinessProcess { get; set; }
        public virtual ICollection<BusinessProcessTemplateDetail> BusinessProcessTemplateDetails { get; set; }
    }
}
