//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacityPlanningScheduleOpenPurchaseOrder
    {
        public int CapacityPlanningScheduleOpenPurchaseOrderPK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> PurchaseOrderNumber { get; set; }
        public Nullable<decimal> PurchaseOrderQuantity { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public byte[] LastAccess { get; set; }
    }
}
