//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commodity
    {
        public Commodity()
        {
            this.CommodityParties = new HashSet<CommodityParty>();
            this.Items = new HashSet<Item>();
            this.LookupTables = new HashSet<LookupTable>();
        }
    
        public int CommodityPK { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<System.DateTime> CostAsOfDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<double> Density { get; set; }
        public string ExternalReferenceID { get; set; }
        public Nullable<short> MCAMType { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<CommodityParty> CommodityParties { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<LookupTable> LookupTables { get; set; }
    }
}
