//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Addresses = new HashSet<Address>();
            this.Form1099Report = new HashSet<Form1099Report>();
            this.HRAddresses = new HashSet<HRAddress>();
            this.ItemSerialNumbers = new HashSet<ItemSerialNumber>();
            this.Projects = new HashSet<Project>();
            this.Regions = new HashSet<Region>();
            this.States = new HashSet<State>();
        }
    
        public int CountryPK { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Form1099Report> Form1099Report { get; set; }
        public virtual ICollection<HRAddress> HRAddresses { get; set; }
        public virtual ICollection<ItemSerialNumber> ItemSerialNumbers { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Region> Regions { get; set; }
        public virtual ICollection<State> States { get; set; }
    }
}
