//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyCode
    {
        public CurrencyCode()
        {
            this.DivisionParameters = new HashSet<DivisionParameter>();
            this.Invoices = new HashSet<Invoice>();
            this.Items = new HashSet<Item>();
            this.Organizations = new HashSet<Organization>();
            this.Parties = new HashSet<Party>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseOrderReceivings = new HashSet<PurchaseOrderReceiving>();
            this.Quotes = new HashSet<Quote>();
            this.RequestForQuotes = new HashSet<RequestForQuote>();
            this.SalesOrders = new HashSet<SalesOrder>();
        }
    
        public int CurrencyCodePK { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> ConversionFactorHome { get; set; }
        public Nullable<decimal> ConversionFactorForeign { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> InvoiceImportExportScriptFK { get; set; }
        public Nullable<int> POReceivingImportExportScriptFK { get; set; }
        public string InvoiceExportFileName { get; set; }
        public string ReceiverExportFileName { get; set; }
    
        public virtual ICollection<DivisionParameter> DivisionParameters { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ImportExportScript ImportExportScript { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<Party> Parties { get; set; }
        public virtual ImportExportScript ImportExportScript1 { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<PurchaseOrderReceiving> PurchaseOrderReceivings { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<RequestForQuote> RequestForQuotes { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
    }
}
