//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class CycleType
    {
        public CycleType()
        {
            this.CompanyBenefits = new HashSet<CompanyBenefit>();
            this.CompanyBenefits1 = new HashSet<CompanyBenefit>();
        }
    
        public int CycleTypePK { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<CompanyBenefit> CompanyBenefits { get; set; }
        public virtual ICollection<CompanyBenefit> CompanyBenefits1 { get; set; }
    }
}
