//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaysOffDivision
    {
        public int DaysOffDivisionPK { get; set; }
        public Nullable<int> DaysOffFK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual DaysOff DaysOff { get; set; }
        public virtual Division Division { get; set; }
    }
}
