//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentPK { get; set; }
        public Nullable<int> DocumentTypeFK { get; set; }
        public Nullable<int> ApprovedByFK { get; set; }
        public Nullable<int> EmployeeFK { get; set; }
        public Nullable<int> EngineeringChangeRequestFK { get; set; }
        public Nullable<int> InvoiceFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> ProjectFK { get; set; }
        public Nullable<int> MachineMaintenanceScheduleFK { get; set; }
        public Nullable<int> MachineMaintenanceScheduleWorkOrderFK { get; set; }
        public Nullable<int> ManifestFK { get; set; }
        public Nullable<int> ManifestLoadFK { get; set; }
        public Nullable<int> RequestForQuoteFK { get; set; }
        public Nullable<int> PartyFK { get; set; }
        public Nullable<int> PurchaseOrderFK { get; set; }
        public Nullable<int> PurchaseOrderReceivingFK { get; set; }
        public Nullable<int> QualityControlFK { get; set; }
        public Nullable<int> QuoteFK { get; set; }
        public Nullable<int> RouterFK { get; set; }
        public Nullable<int> RouterWorkCenterFK { get; set; }
        public Nullable<int> SalesOrderFK { get; set; }
        public Nullable<int> WorkOrderFK { get; set; }
        public Nullable<int> WorkOrderNestFK { get; set; }
        public string URL { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> PrintWithWorkOrder { get; set; }
        public Nullable<bool> PrintWithPackingSlip { get; set; }
        public Nullable<bool> SecureDocument { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Revision { get; set; }
        public string LotNumber { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> CustomerPaymentFK { get; set; }
        public Nullable<bool> PrintAsThumbnail { get; set; }
        public Nullable<bool> PrintWithPurchaseOrder { get; set; }
        public Nullable<int> DocumentGroupFK { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<int> BillFK { get; set; }
        public Nullable<int> TaskActivityFK { get; set; }
        public Nullable<bool> PrintWithInvoice { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual CustomerPayment CustomerPayment { get; set; }
        public virtual User User { get; set; }
        public virtual DocumentGroup DocumentGroup { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual EngineeringChangeRequest EngineeringChangeRequest { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Item Item { get; set; }
        public virtual MachineMaintenanceSchedule MachineMaintenanceSchedule { get; set; }
        public virtual MachineMaintenanceScheduleWorkOrder MachineMaintenanceScheduleWorkOrder { get; set; }
        public virtual Manifest Manifest { get; set; }
        public virtual ManifestLoad ManifestLoad { get; set; }
        public virtual Party Party { get; set; }
        public virtual Project Project { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual PurchaseOrderReceiving PurchaseOrderReceiving { get; set; }
        public virtual QualityControl QualityControl { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual RequestForQuote RequestForQuote { get; set; }
        public virtual Router Router { get; set; }
        public virtual RouterWorkCenter RouterWorkCenter { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual TaskActivity TaskActivity { get; set; }
        public virtual User User1 { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual WorkOrderNest WorkOrderNest { get; set; }
    }
}
