//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicSalesOrderLine
    {
        public int ElectronicSalesOrderLinePK { get; set; }
        public Nullable<int> ElectronicSalesOrderFK { get; set; }
        public Nullable<int> CustomerFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> ShipViaFK { get; set; }
        public Nullable<int> TermsFK { get; set; }
        public Nullable<int> JobNumber { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public string ReleaseNumber { get; set; }
        public Nullable<int> SalesOrderNumber { get; set; }
        public Nullable<int> SalesOrderLineLotNumber { get; set; }
        public Nullable<bool> AddressMismatch { get; set; }
        public Nullable<bool> PartNumberMismatch { get; set; }
        public Nullable<bool> PriceMismatch { get; set; }
        public Nullable<bool> RevisionMismatch { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> StockLength { get; set; }
        public Nullable<decimal> StockWidth { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ImportedPrice { get; set; }
        public string BillToCode { get; set; }
        public string ShipToCode { get; set; }
        public string Revision { get; set; }
        public string ImportedRevision { get; set; }
        public string ItemNumber { get; set; }
        public string Item { get; set; }
        public string FOB { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string SenderID { get; set; }
        public string UserDefinedPO { get; set; }
        public string Attention { get; set; }
        public string PartNumber { get; set; }
        public string VendorPartNumber { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string AddressAlt { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }
        public string CustomDescription { get; set; }
        public string Comment { get; set; }
        public string LastDeliveryInvoice { get; set; }
        public Nullable<decimal> LastDeliveryQuantity { get; set; }
        public string DocType { get; set; }
        public string ShippingName { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingAddress3 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingZip { get; set; }
        public string Status { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ElectronicSalesOrder ElectronicSalesOrder { get; set; }
        public virtual Party Party { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual ShipVia ShipVia { get; set; }
        public virtual Term Term { get; set; }
    }
}
