//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiscalCalendar
    {
        public FiscalCalendar()
        {
            this.Budgets = new HashSet<Budget>();
            this.BudgetAccounts = new HashSet<BudgetAccount>();
            this.DivisionParameters = new HashSet<DivisionParameter>();
            this.Form1099Report = new HashSet<Form1099Report>();
            this.ItemMasterProductionSchedules = new HashSet<ItemMasterProductionSchedule>();
        }
    
        public int FiscalCalendarPK { get; set; }
        public string Description { get; set; }
        public string Period1Description { get; set; }
        public Nullable<System.DateTime> Period1DateFrom { get; set; }
        public Nullable<System.DateTime> Period1DateTo { get; set; }
        public string Period2Description { get; set; }
        public Nullable<System.DateTime> Period2DateFrom { get; set; }
        public Nullable<System.DateTime> Period2DateTo { get; set; }
        public string Period3Description { get; set; }
        public Nullable<System.DateTime> Period3DateFrom { get; set; }
        public Nullable<System.DateTime> Period3DateTo { get; set; }
        public string Period4Description { get; set; }
        public Nullable<System.DateTime> Period4DateFrom { get; set; }
        public Nullable<System.DateTime> Period4DateTo { get; set; }
        public string Period5Description { get; set; }
        public Nullable<System.DateTime> Period5DateFrom { get; set; }
        public Nullable<System.DateTime> Period5DateTo { get; set; }
        public string Period6Description { get; set; }
        public Nullable<System.DateTime> Period6DateFrom { get; set; }
        public Nullable<System.DateTime> Period6DateTo { get; set; }
        public string Period7Description { get; set; }
        public Nullable<System.DateTime> Period7DateFrom { get; set; }
        public Nullable<System.DateTime> Period7DateTo { get; set; }
        public string Period8Description { get; set; }
        public Nullable<System.DateTime> Period8DateFrom { get; set; }
        public Nullable<System.DateTime> Period8DateTo { get; set; }
        public string Period9Description { get; set; }
        public Nullable<System.DateTime> Period9DateFrom { get; set; }
        public Nullable<System.DateTime> Period9DateTo { get; set; }
        public string Period10Description { get; set; }
        public Nullable<System.DateTime> Period10DateFrom { get; set; }
        public Nullable<System.DateTime> Period10DateTo { get; set; }
        public string Period11Description { get; set; }
        public Nullable<System.DateTime> Period11DateFrom { get; set; }
        public Nullable<System.DateTime> Period11DateTo { get; set; }
        public string Period12Description { get; set; }
        public Nullable<System.DateTime> Period12DateFrom { get; set; }
        public Nullable<System.DateTime> Period12DateTo { get; set; }
        public string Period13Description { get; set; }
        public Nullable<System.DateTime> Period13DateFrom { get; set; }
        public Nullable<System.DateTime> Period13DateTo { get; set; }
        public Nullable<System.DateTime> Quarter1DateFrom { get; set; }
        public Nullable<System.DateTime> Quarter1DateTo { get; set; }
        public Nullable<System.DateTime> Quarter2DateFrom { get; set; }
        public Nullable<System.DateTime> Quarter2DateTo { get; set; }
        public Nullable<System.DateTime> Quarter3DateFrom { get; set; }
        public Nullable<System.DateTime> Quarter3DateTo { get; set; }
        public Nullable<System.DateTime> Quarter4DateFrom { get; set; }
        public Nullable<System.DateTime> Quarter4DateTo { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual ICollection<BudgetAccount> BudgetAccounts { get; set; }
        public virtual ICollection<DivisionParameter> DivisionParameters { get; set; }
        public virtual ICollection<Form1099Report> Form1099Report { get; set; }
        public virtual ICollection<ItemMasterProductionSchedule> ItemMasterProductionSchedules { get; set; }
    }
}
