//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedAsset
    {
        public int FixedAssetPK { get; set; }
        public Nullable<int> MachineFK { get; set; }
        public Nullable<bool> ActiveRepairCostFlag { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> FullDepreciatedDate { get; set; }
        public Nullable<System.DateTime> ServiceStartDate { get; set; }
        public Nullable<decimal> AdditionalCost { get; set; }
        public Nullable<decimal> EconomicLife { get; set; }
        public Nullable<decimal> ResidualValue { get; set; }
        public Nullable<decimal> MonthlyDepreciation { get; set; }
        public Nullable<int> MonthsOfDepreciation { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> RepairCostTotal { get; set; }
        public string Comment { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
