//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form1099ReportParty
    {
        public int Form1099ReportPartyPK { get; set; }
        public Nullable<int> Form1099ReportFK { get; set; }
        public Nullable<int> PartyFK { get; set; }
        public Nullable<decimal> Box1 { get; set; }
        public Nullable<decimal> Box2 { get; set; }
        public Nullable<decimal> Box3 { get; set; }
        public Nullable<decimal> Box4 { get; set; }
        public Nullable<decimal> Box5 { get; set; }
        public Nullable<decimal> Box6 { get; set; }
        public Nullable<decimal> Box7 { get; set; }
        public Nullable<decimal> Box8 { get; set; }
        public Nullable<bool> Box9 { get; set; }
        public Nullable<decimal> Box10 { get; set; }
        public Nullable<decimal> Box11 { get; set; }
        public string Box12 { get; set; }
        public Nullable<decimal> Box13 { get; set; }
        public Nullable<decimal> Box14 { get; set; }
        public Nullable<decimal> Box15A { get; set; }
        public Nullable<decimal> Box15B { get; set; }
        public Nullable<decimal> Box16 { get; set; }
        public string Box17 { get; set; }
        public Nullable<decimal> Box18 { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Form1099Report Form1099Report { get; set; }
        public virtual Party Party { get; set; }
    }
}
