//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreightCode
    {
        public FreightCode()
        {
            this.Addresses = new HashSet<Address>();
            this.Invoices = new HashSet<Invoice>();
            this.Manifests = new HashSet<Manifest>();
            this.Parties = new HashSet<Party>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.SalesOrders = new HashSet<SalesOrder>();
        }
    
        public int FreightCodePK { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Manifest> Manifests { get; set; }
        public virtual ICollection<Party> Parties { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
    }
}
