//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralJournalEntry
    {
        public GeneralJournalEntry()
        {
            this.CustomerAgings = new HashSet<CustomerAging>();
            this.GeneralJournalEntryLines = new HashSet<GeneralJournalEntryLine>();
            this.GeneralLedgerDetails = new HashSet<GeneralLedgerDetail>();
        }
    
        public int GeneralJournalEntryPK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public Nullable<int> GeneralJournalEntryStatusFK { get; set; }
        public Nullable<int> GeneralJournalEntryNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<bool> ReversingEntry { get; set; }
        public byte[] LastAccess { get; set; }
        public string Memo { get; set; }
        public Nullable<int> MemorizedJournalEntryNumber { get; set; }
    
        public virtual ICollection<CustomerAging> CustomerAgings { get; set; }
        public virtual Division Division { get; set; }
        public virtual GeneralJournalEntryStatu GeneralJournalEntryStatu { get; set; }
        public virtual ICollection<GeneralJournalEntryLine> GeneralJournalEntryLines { get; set; }
        public virtual ICollection<GeneralLedgerDetail> GeneralLedgerDetails { get; set; }
    }
}
