//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralLedgerSummaryTotal
    {
        public int GeneralLedgerSummaryTotalPK { get; set; }
        public Nullable<int> GeneralLedgerAccountFK { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountOnReport { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual GeneralLedgerAccount GeneralLedgerAccount { get; set; }
    }
}
