//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREvaluationScore
    {
        public int HREvaluationScorePK { get; set; }
        public Nullable<int> HREvaluationCategoryFK { get; set; }
        public Nullable<int> HREvaluationFK { get; set; }
        public int Score { get; set; }
        public int MaxScore { get; set; }
        public string Comment { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual HREvaluation HREvaluation { get; set; }
        public virtual HREvaluationCategory HREvaluationCategory { get; set; }
    }
}
