//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRWarning
    {
        public int HRWarningPK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> IssuedByFK { get; set; }
        public Nullable<int> UserCodeItemFK { get; set; }
        public string IssuedByDescription { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string Summary { get; set; }
        public string ActionTaken { get; set; }
        public string EmployeeComments { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual UserCodeItem UserCodeItem { get; set; }
    }
}
