//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationTransaction
    {
        public int IntegrationTransactionPK { get; set; }
        public string Topic { get; set; }
        public string Action { get; set; }
        public string EntityKey { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public byte[] LastAccess { get; set; }
    }
}
