//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrityCheck
    {
        public int IntegrityCheckPK { get; set; }
        public string Description { get; set; }
        public string FunctionName { get; set; }
        public Nullable<bool> RequiredDivision { get; set; }
        public Nullable<System.DateTime> LastRunTime { get; set; }
        public Nullable<bool> IsSuccessful { get; set; }
        public Nullable<int> Project { get; set; }
        public byte[] LastAccess { get; set; }
    }
}
