//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePayment
    {
        public int InvoicePaymentPK { get; set; }
        public int InvoiceFK { get; set; }
        public Nullable<int> PaymentNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string ReferenceNumber { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
