//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInventoryWorkSheet
    {
        public ItemInventoryWorkSheet()
        {
            this.ItemInventoryWorkSheetItems = new HashSet<ItemInventoryWorkSheetItem>();
        }
    
        public int ItemInventoryWorkSheetPK { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<ItemInventoryWorkSheetItem> ItemInventoryWorkSheetItems { get; set; }
    }
}
