//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemVendor
    {
        public int ItemVendorPK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> PartyFK { get; set; }
        public Nullable<bool> Customer { get; set; }
        public Nullable<bool> ItemVendorPrimary { get; set; }
        public Nullable<bool> OutsideProcessing { get; set; }
        public Nullable<bool> Vendor { get; set; }
        public string VendorPartNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> GoodUntil { get; set; }
        public Nullable<decimal> Quantity1 { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> MarkupPercentage1 { get; set; }
        public Nullable<decimal> SellPrice1 { get; set; }
        public Nullable<decimal> MSRP1 { get; set; }
        public Nullable<decimal> Quantity2 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> MarkupPercentage2 { get; set; }
        public Nullable<decimal> SellPrice2 { get; set; }
        public Nullable<decimal> MSRP2 { get; set; }
        public Nullable<decimal> Quantity3 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<decimal> MarkupPercentage3 { get; set; }
        public Nullable<decimal> SellPrice3 { get; set; }
        public Nullable<decimal> MSRP3 { get; set; }
        public Nullable<decimal> Quantity4 { get; set; }
        public Nullable<decimal> Price4 { get; set; }
        public Nullable<decimal> MarkupPercentage4 { get; set; }
        public Nullable<decimal> SellPrice4 { get; set; }
        public Nullable<decimal> MSRP4 { get; set; }
        public Nullable<decimal> Quantity5 { get; set; }
        public Nullable<decimal> Price5 { get; set; }
        public Nullable<decimal> MarkupPercentage5 { get; set; }
        public Nullable<decimal> SellPrice5 { get; set; }
        public Nullable<decimal> MSRP5 { get; set; }
        public Nullable<decimal> Quantity6 { get; set; }
        public Nullable<decimal> Price6 { get; set; }
        public Nullable<decimal> MarkupPercentage6 { get; set; }
        public Nullable<decimal> SellPrice6 { get; set; }
        public Nullable<decimal> MSRP6 { get; set; }
        public Nullable<decimal> Quantity7 { get; set; }
        public Nullable<decimal> Price7 { get; set; }
        public Nullable<decimal> MarkupPercentage7 { get; set; }
        public Nullable<decimal> SellPrice7 { get; set; }
        public Nullable<decimal> MSRP7 { get; set; }
        public Nullable<decimal> Quantity8 { get; set; }
        public Nullable<decimal> Price8 { get; set; }
        public Nullable<decimal> MarkupPercentage8 { get; set; }
        public Nullable<decimal> SellPrice8 { get; set; }
        public Nullable<decimal> MSRP8 { get; set; }
        public string Comment { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<decimal> Minimum { get; set; }
        public string VendorRevision { get; set; }
        public Nullable<int> CustomerGroupFK { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string PriceComments1 { get; set; }
        public string PriceComments2 { get; set; }
        public string PriceComments3 { get; set; }
        public string PriceComments4 { get; set; }
        public string PriceComments5 { get; set; }
        public string PriceComments6 { get; set; }
        public string PriceComments7 { get; set; }
        public string PriceComments8 { get; set; }
    
        public virtual CustomerGroup CustomerGroup { get; set; }
        public virtual Item Item { get; set; }
        public virtual Party Party { get; set; }
    }
}
