//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSerialNumber
    {
        public int ItemSerialNumberPK { get; set; }
        public Nullable<int> CustomerFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> InvoiceLineFK { get; set; }
        public Nullable<int> StateFK { get; set; }
        public Nullable<int> CountryFK { get; set; }
        public string SerialNumber { get; set; }
        public string LotNumber { get; set; }
        public string WorkOrderNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> WarrantyDate { get; set; }
        public string Notes { get; set; }
        public string WarrantyNotes { get; set; }
        public string EndUser { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string AddressAlt { get; set; }
        public string AddressCity { get; set; }
        public string AddressZipCode { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> PurchaseOrderReceivingLine { get; set; }
        public string ManufacturerSerialNumber { get; set; }
        public string UserDefinedChar1 { get; set; }
        public string UserDefinedChar2 { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual InvoiceLine InvoiceLine { get; set; }
        public virtual Item Item { get; set; }
        public virtual Party Party { get; set; }
        public virtual State State { get; set; }
    }
}
