//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSubstitution
    {
        public int ItemSubstitutionPK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> SubstituteFK { get; set; }
        public Nullable<int> PartyFK { get; set; }
        public Nullable<bool> PullItemAtReceiving { get; set; }
        public Nullable<decimal> QuantityRequired { get; set; }
        public string PartNumber { get; set; }
        public string Revision { get; set; }
        public string Description { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual Party Party { get; set; }
    }
}
