//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class LockedFile
    {
        public int LockedFilePK { get; set; }
        public int FileTypeFK { get; set; }
        public int UserFK { get; set; }
        public int FileId { get; set; }
        public System.DateTime DateStamp { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual LockedFileType LockedFileType { get; set; }
        public virtual User User { get; set; }
    }
}
