//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineUsageReading
    {
        public int MachineUsageReadingPK { get; set; }
        public Nullable<int> MachineUsageReadingTypeFK { get; set; }
        public Nullable<int> MachineFK { get; set; }
        public Nullable<decimal> ReadingValue { get; set; }
        public Nullable<System.DateTime> LastReadingDate { get; set; }
        public string Reader { get; set; }
        public string Comment { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual MachineUsageReadingType MachineUsageReadingType { get; set; }
    }
}
