//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManifestLine
    {
        public int ManifestLinePK { get; set; }
        public Nullable<int> ManifestFK { get; set; }
        public Nullable<int> InvoiceLineFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> UnitOfMeasureSetFK { get; set; }
        public Nullable<decimal> StockLength { get; set; }
        public Nullable<decimal> StockWidth { get; set; }
        public Nullable<decimal> PieceWeight { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Revision { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string PartNumber { get; set; }
        public string CustomDescription { get; set; }
        public string Notes { get; set; }
        public string ShippingNotes { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> FreightClassFK { get; set; }
    
        public virtual FreightClass FreightClass { get; set; }
        public virtual InvoiceLine InvoiceLine { get; set; }
        public virtual Item Item { get; set; }
        public virtual Manifest Manifest { get; set; }
        public virtual UnitOfMeasureSet UnitOfMeasureSet { get; set; }
    }
}
