//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartySupplier
    {
        public int PartySupplierPK { get; set; }
        public Nullable<int> PartyFK { get; set; }
        public Nullable<int> SupplierFK { get; set; }
        public Nullable<int> QualityLevelFK { get; set; }
        public Nullable<System.DateTime> LastAuditDate { get; set; }
        public Nullable<System.DateTime> LastReviewDate { get; set; }
        public string Fax { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual Party Party1 { get; set; }
        public virtual QualityLevel QualityLevel { get; set; }
    }
}
