//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPeriod
    {
        public PayPeriod()
        {
            this.TimeCards = new HashSet<TimeCard>();
        }
    
        public int PayPeriodPK { get; set; }
        public Nullable<int> PayrollCycleFK { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual PayrollCycle PayrollCycle { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
    }
}
