//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            this.Documents = new HashSet<Document>();
            this.PurchaseOrderLines = new HashSet<PurchaseOrderLine>();
            this.PurchaseOrderSuppliers = new HashSet<PurchaseOrderSupplier>();
            this.TaskActivities = new HashSet<TaskActivity>();
            this.WorkOrderIssuings = new HashSet<WorkOrderIssuing>();
        }
    
        public int PurchaseOrderPK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public Nullable<int> SupplierFK { get; set; }
        public Nullable<int> BillingAddressFK { get; set; }
        public Nullable<int> CustomerFK { get; set; }
        public Nullable<int> ShippingAddressFK { get; set; }
        public Nullable<int> ConfirmingStatementFK { get; set; }
        public Nullable<int> RequisitionerFK { get; set; }
        public Nullable<int> OrderByFK { get; set; }
        public Nullable<int> SalesPersonFK { get; set; }
        public Nullable<int> ShipViaFK { get; set; }
        public Nullable<int> TermFK { get; set; }
        public Nullable<int> FreightCodeFK { get; set; }
        public Nullable<int> CurrencyCodeFK { get; set; }
        public Nullable<int> PurchaseOrderStatusFK { get; set; }
        public Nullable<int> PurchaseOrderNumber { get; set; }
        public string ExternalReferenceNumber { get; set; }
        public string BlanketPurchaseOrderNumber { get; set; }
        public Nullable<System.DateTime> BlanketPurchaseOrderGoodUntil { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<System.DateTime> PORequiredDate { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<bool> PurchaseOrderPrinted { get; set; }
        public Nullable<bool> ReceivingHold { get; set; }
        public Nullable<bool> PurchaseOrderRejected { get; set; }
        public string PurchaseOrderRejectedReference { get; set; }
        public string FreightOnBoard { get; set; }
        public Nullable<decimal> ConversionValue { get; set; }
        public Nullable<bool> ShowByHomeCurrency { get; set; }
        public Nullable<bool> ShipToCustomer { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> NonTaxableAmount { get; set; }
        public Nullable<decimal> SalesTax1Amount { get; set; }
        public Nullable<decimal> SalesTax2Amount { get; set; }
        public Nullable<decimal> SalesTax3Amount { get; set; }
        public Nullable<decimal> SalesTax4Amount { get; set; }
        public Nullable<decimal> FreightCharge { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> ForeignCurrencyTaxableAmount { get; set; }
        public Nullable<decimal> ForeignCurrencyNonTaxableAmount { get; set; }
        public Nullable<decimal> ForeignCurrencyMiscellaneousAmount { get; set; }
        public Nullable<decimal> ForeignCurrencySalesTax1Amount { get; set; }
        public Nullable<decimal> ForeignCurrencySalesTax2Amount { get; set; }
        public Nullable<decimal> ForeignCurrencySalesTax3Amount { get; set; }
        public Nullable<decimal> ForeignCurrencySalesTax4Amount { get; set; }
        public Nullable<decimal> ForeignCurrencyFreightCharge { get; set; }
        public Nullable<decimal> ForeignCurrencyTotalAmount { get; set; }
        public Nullable<System.DateTime> UserDefinedDate1 { get; set; }
        public Nullable<System.DateTime> UserDefinedDate2 { get; set; }
        public Nullable<System.DateTime> UserDefinedDate3 { get; set; }
        public Nullable<bool> UserDefinedBit1 { get; set; }
        public Nullable<bool> UserDefinedBit2 { get; set; }
        public Nullable<bool> UserDefinedBit3 { get; set; }
        public string UserDefinedText1 { get; set; }
        public string UserDefinedText2 { get; set; }
        public string UserDefinedText3 { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> PopupNotifyComment { get; set; }
        public string NotifyComment { get; set; }
        public string BillingAddressName { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingAddressAlt { get; set; }
        public string BillingAddressCity { get; set; }
        public string BillingAddressZipCode { get; set; }
        public string ShippingAddressName { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingAddressAlt { get; set; }
        public string ShippingAddressCity { get; set; }
        public string ShippingAddressZipCode { get; set; }
        public string SalesTax1Name { get; set; }
        public Nullable<decimal> SalesTax1Rate { get; set; }
        public string SalesTaxType1Description { get; set; }
        public string SalesTax2Name { get; set; }
        public Nullable<decimal> SalesTax2Rate { get; set; }
        public string SalesTaxType2Description { get; set; }
        public string SalesTax3Name { get; set; }
        public Nullable<decimal> SalesTax3Rate { get; set; }
        public string SalesTaxType3Description { get; set; }
        public string SalesTax4Name { get; set; }
        public Nullable<decimal> SalesTax4Rate { get; set; }
        public string SalesTaxType4Description { get; set; }
        public Nullable<bool> BlanketPurchaseOrder { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<bool> RequiresApproval { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> RequestDeniedDate { get; set; }
        public Nullable<bool> SalesTaxOnFreight { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<bool> Emailed { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ConfirmingStatement ConfirmingStatement { get; set; }
        public virtual CurrencyCode CurrencyCode { get; set; }
        public virtual Division Division { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual FreightCode FreightCode { get; set; }
        public virtual Party Party { get; set; }
        public virtual Party Party1 { get; set; }
        public virtual Party Party2 { get; set; }
        public virtual PurchaseOrderStatu PurchaseOrderStatu { get; set; }
        public virtual ShipVia ShipVia { get; set; }
        public virtual Term Term { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; }
        public virtual ICollection<PurchaseOrderSupplier> PurchaseOrderSuppliers { get; set; }
        public virtual ICollection<TaskActivity> TaskActivities { get; set; }
        public virtual ICollection<WorkOrderIssuing> WorkOrderIssuings { get; set; }
    }
}
