//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRFQSupplierLine
    {
        public int PurchaseRFQSupplierLinePK { get; set; }
        public Nullable<int> PurchaseRFQSupplierFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> PurchaseRFQLine { get; set; }
        public string PartNumber { get; set; }
        public string Revision { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> StockWidth { get; set; }
        public Nullable<decimal> StockLength { get; set; }
        public string ExternalReferenceNumber { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Quantity1 { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> Quantity2 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Quantity3 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<decimal> Quantity4 { get; set; }
        public Nullable<decimal> Price4 { get; set; }
        public Nullable<decimal> Quantity5 { get; set; }
        public Nullable<decimal> Price5 { get; set; }
        public Nullable<decimal> Quantity6 { get; set; }
        public Nullable<decimal> Price6 { get; set; }
        public Nullable<decimal> Quantity7 { get; set; }
        public Nullable<decimal> Price7 { get; set; }
        public Nullable<decimal> Quantity8 { get; set; }
        public Nullable<decimal> Price8 { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual PurchaseRFQSupplier PurchaseRFQSupplier { get; set; }
    }
}
