//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuickViewParameterMaster
    {
        public int QuickViewParameterMasterPK { get; set; }
        public Nullable<int> QuickViewMasterFK { get; set; }
        public Nullable<int> QuickViewParameterTypeFK { get; set; }
        public string ParameterName { get; set; }
        public string DefaultValue { get; set; }
        public string ValueList { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual QuickViewMaster QuickViewMaster { get; set; }
        public virtual QuickViewParameterType QuickViewParameterType { get; set; }
    }
}
