//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReminderType
    {
        public ReminderType()
        {
            this.MachineMaintenanceReminders = new HashSet<MachineMaintenanceReminder>();
            this.MachineMaintenanceReminders1 = new HashSet<MachineMaintenanceReminder>();
            this.MachineMaintenanceReminders2 = new HashSet<MachineMaintenanceReminder>();
            this.MachineMaintenanceReminders3 = new HashSet<MachineMaintenanceReminder>();
            this.MachineMaintenanceReminders4 = new HashSet<MachineMaintenanceReminder>();
            this.MachineMaintenanceReminders5 = new HashSet<MachineMaintenanceReminder>();
        }
    
        public int ReminderTypePK { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ReminderFlags { get; set; }
        public Nullable<int> ReminderFlagsProgress { get; set; }
        public string ReminderTarget1 { get; set; }
        public string ReminderTarget2 { get; set; }
        public string ReminderTarget3 { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<MachineMaintenanceReminder> MachineMaintenanceReminders { get; set; }
        public virtual ICollection<MachineMaintenanceReminder> MachineMaintenanceReminders1 { get; set; }
        public virtual ICollection<MachineMaintenanceReminder> MachineMaintenanceReminders2 { get; set; }
        public virtual ICollection<MachineMaintenanceReminder> MachineMaintenanceReminders3 { get; set; }
        public virtual ICollection<MachineMaintenanceReminder> MachineMaintenanceReminders4 { get; set; }
        public virtual ICollection<MachineMaintenanceReminder> MachineMaintenanceReminders5 { get; set; }
    }
}
