//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportFilterCriteria
    {
        public int ReportFilterCriteriaPK { get; set; }
        public string ReportFilterName { get; set; }
        public Nullable<int> ReportTypeFK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public Nullable<bool> PublicFlag { get; set; }
        public string Criteria01 { get; set; }
        public string Criteria02 { get; set; }
        public string Criteria03 { get; set; }
        public string Criteria04 { get; set; }
        public string Criteria05 { get; set; }
        public string Criteria06 { get; set; }
        public string Criteria07 { get; set; }
        public string Criteria08 { get; set; }
        public string Criteria09 { get; set; }
        public string Criteria10 { get; set; }
        public string Criteria11 { get; set; }
        public string Criteria12 { get; set; }
        public string Criteria13 { get; set; }
        public string Criteria14 { get; set; }
        public string Criteria15 { get; set; }
        public string Criteria16 { get; set; }
        public string Criteria17 { get; set; }
        public string Criteria18 { get; set; }
        public string Criteria19 { get; set; }
        public string Criteria20 { get; set; }
        public string Criteria21 { get; set; }
        public string Criteria22 { get; set; }
        public string Criteria23 { get; set; }
        public string Criteria24 { get; set; }
        public string Criteria25 { get; set; }
        public string Criteria26 { get; set; }
        public string Criteria27 { get; set; }
        public string Criteria28 { get; set; }
        public string Criteria29 { get; set; }
        public string Criteria30 { get; set; }
        public string Criteria31 { get; set; }
        public string Criteria32 { get; set; }
        public string Criteria33 { get; set; }
        public string Criteria34 { get; set; }
        public string Criteria35 { get; set; }
        public string Criteria36 { get; set; }
        public string Criteria37 { get; set; }
        public string Criteria38 { get; set; }
        public string Criteria39 { get; set; }
        public string Criteria40 { get; set; }
        public string Criteria41 { get; set; }
        public string Criteria42 { get; set; }
        public string Criteria43 { get; set; }
        public string Criteria44 { get; set; }
        public string Criteria45 { get; set; }
        public string Criteria46 { get; set; }
        public string Criteria47 { get; set; }
        public string Criteria48 { get; set; }
        public string Criteria49 { get; set; }
        public string Criteria50 { get; set; }
        public string Criteria51 { get; set; }
        public string Criteria52 { get; set; }
        public string Criteria53 { get; set; }
        public string Criteria54 { get; set; }
        public string Criteria55 { get; set; }
        public string Criteria56 { get; set; }
        public string Criteria57 { get; set; }
        public string Criteria58 { get; set; }
        public string Criteria59 { get; set; }
        public string Criteria60 { get; set; }
        public Nullable<System.DateTime> Date01 { get; set; }
        public Nullable<System.DateTime> Date02 { get; set; }
        public Nullable<System.DateTime> Date03 { get; set; }
        public Nullable<System.DateTime> Date04 { get; set; }
        public Nullable<System.DateTime> Date05 { get; set; }
        public Nullable<System.DateTime> Date06 { get; set; }
        public Nullable<System.DateTime> Date07 { get; set; }
        public Nullable<System.DateTime> Date08 { get; set; }
        public Nullable<System.DateTime> Date09 { get; set; }
        public Nullable<System.DateTime> Date10 { get; set; }
        public Nullable<System.DateTime> Date11 { get; set; }
        public Nullable<System.DateTime> Date12 { get; set; }
        public Nullable<System.DateTime> Date13 { get; set; }
        public Nullable<System.DateTime> Date14 { get; set; }
        public byte[] LastAccess { get; set; }
        public string Criteria61 { get; set; }
        public string Criteria62 { get; set; }
        public string Criteria63 { get; set; }
        public string Criteria64 { get; set; }
        public string Criteria65 { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual ReportType ReportType { get; set; }
        public virtual User User { get; set; }
    }
}
