//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportType
    {
        public ReportType()
        {
            this.Reports = new HashSet<Report>();
            this.ReportFilterCriterias = new HashSet<ReportFilterCriteria>();
            this.ReportTemplates = new HashSet<ReportTemplate>();
        }
    
        public int ReportTypePK { get; set; }
        public Nullable<int> ReportGroupFK { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<ReportFilterCriteria> ReportFilterCriterias { get; set; }
        public virtual ReportGroup ReportGroup { get; set; }
        public virtual ICollection<ReportTemplate> ReportTemplates { get; set; }
    }
}
