//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestForQuoteLineQuantity
    {
        public int RequestForQuoteLineQuantityPK { get; set; }
        public Nullable<int> RequestForQuoteLineFK { get; set; }
        public Nullable<int> PriceTypeFK { get; set; }
        public Nullable<int> AlternativeUnitOfMeasureSetFK { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> CutQuantity { get; set; }
        public Nullable<decimal> Delivery { get; set; }
        public Nullable<decimal> MarkupPercentage { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
        public Nullable<decimal> EstimatedHours { get; set; }
        public Nullable<decimal> SetupTime { get; set; }
        public Nullable<decimal> SetupLaborCost { get; set; }
        public Nullable<decimal> SetupEquipmentCharge { get; set; }
        public Nullable<decimal> SetupCost { get; set; }
        public Nullable<decimal> SetupPrice { get; set; }
        public Nullable<decimal> RunTime { get; set; }
        public Nullable<decimal> RunLaborCost { get; set; }
        public Nullable<decimal> RunEquipmentCharge { get; set; }
        public Nullable<decimal> RunCost { get; set; }
        public Nullable<decimal> RunPrice { get; set; }
        public Nullable<decimal> MaterialUnitCost { get; set; }
        public Nullable<decimal> MaterialUnitPrice { get; set; }
        public Nullable<decimal> HardwareUnitCost { get; set; }
        public Nullable<decimal> KitCost { get; set; }
        public Nullable<decimal> KitPrice { get; set; }
        public Nullable<decimal> StandardCost { get; set; }
        public Nullable<decimal> StandardPrice { get; set; }
        public Nullable<decimal> MiscellaneousCost { get; set; }
        public Nullable<decimal> MiscellaneousPrice { get; set; }
        public Nullable<decimal> HardwareUnitPrice { get; set; }
        public Nullable<decimal> OutsideProcessingUnitCost { get; set; }
        public Nullable<decimal> OutsideProcessingUnitPrice { get; set; }
        public Nullable<decimal> ToolingCharge { get; set; }
        public Nullable<decimal> TargetPrice { get; set; }
        public Nullable<bool> PrimaryPrice { get; set; }
        public Nullable<decimal> AlternativeQuantity { get; set; }
        public Nullable<decimal> AlternativePrice { get; set; }
        public Nullable<decimal> VendorUnit { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public string UserDefinedChar1 { get; set; }
        public string UserDefinedChar2 { get; set; }
    
        public virtual PriceType PriceType { get; set; }
        public virtual RequestForQuoteLine RequestForQuoteLine { get; set; }
        public virtual UnitOfMeasureSet UnitOfMeasureSet { get; set; }
    }
}
