//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestForQuoteLine
    {
        public RequestForQuoteLine()
        {
            this.ElectronicRequestForQuoteLines = new HashSet<ElectronicRequestForQuoteLine>();
            this.Kits = new HashSet<Kit>();
            this.QuoteAssemblies = new HashSet<QuoteAssembly>();
            this.RequestForQuoteLineQuantities = new HashSet<RequestForQuoteLineQuantity>();
            this.TaskJournals = new HashSet<TaskJournal>();
        }
    
        public int RequestForQuoteLinePK { get; set; }
        public Nullable<int> AlternativeUnitOfMeasureSetFK { get; set; }
        public Nullable<int> AssignedEstimatorFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> KitComponentsShowTypeFK { get; set; }
        public Nullable<int> PriceTypeFK { get; set; }
        public Nullable<int> QuoteFK { get; set; }
        public Nullable<int> RequestForQuoteFK { get; set; }
        public Nullable<int> UnitOfMeasureSetFK { get; set; }
        public Nullable<bool> QuoteRequired { get; set; }
        public Nullable<bool> QuoteCompleted { get; set; }
        public Nullable<bool> QuoteApproved { get; set; }
        public Nullable<bool> DidNotGet { get; set; }
        public Nullable<bool> Capture { get; set; }
        public Nullable<decimal> CapturePrice { get; set; }
        public Nullable<decimal> CaptureQuantity { get; set; }
        public Nullable<decimal> KitPrice { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public Nullable<bool> Commissionable { get; set; }
        public Nullable<bool> Discount { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> LastDateUpdated { get; set; }
        public Nullable<System.DateTime> QuoteLastUpdateDate { get; set; }
        public string CustomDescription { get; set; }
        public string Availability { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> MarkupPercentage { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
        public Nullable<decimal> EstimatedHours { get; set; }
        public Nullable<decimal> SetupTime { get; set; }
        public Nullable<decimal> SetupLaborCost { get; set; }
        public Nullable<decimal> SetupEquipmentCharge { get; set; }
        public Nullable<decimal> MiscellaneousPrice { get; set; }
        public Nullable<decimal> StandardPrice { get; set; }
        public Nullable<decimal> MiscellaneousCost { get; set; }
        public Nullable<decimal> StandardCost { get; set; }
        public Nullable<decimal> KitCost { get; set; }
        public Nullable<decimal> SetupCost { get; set; }
        public Nullable<decimal> SetupPrice { get; set; }
        public Nullable<decimal> RunTime { get; set; }
        public Nullable<decimal> RunLaborCost { get; set; }
        public Nullable<decimal> RunEquipmentCharge { get; set; }
        public Nullable<decimal> RunCost { get; set; }
        public Nullable<decimal> RunPrice { get; set; }
        public Nullable<decimal> LaborCost { get; set; }
        public Nullable<decimal> EquipmentCharge { get; set; }
        public Nullable<decimal> MaterialUnitCost { get; set; }
        public Nullable<decimal> MaterialUnitPrice { get; set; }
        public Nullable<decimal> HardwareUnitCost { get; set; }
        public Nullable<decimal> HardwareUnitPrice { get; set; }
        public Nullable<decimal> OutsideProcessingUnitCost { get; set; }
        public Nullable<decimal> OutsideProcessingUnitPrice { get; set; }
        public Nullable<decimal> ToolingCharge { get; set; }
        public Nullable<decimal> AlternativeQuantity { get; set; }
        public Nullable<decimal> AlternativePrice { get; set; }
        public Nullable<decimal> VendorUnit { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> LineReferenceNumber { get; set; }
        public Nullable<bool> NoBid { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public Nullable<int> JobNumber { get; set; }
        public Nullable<System.DateTime> CapturedDate { get; set; }
    
        public virtual ICollection<ElectronicRequestForQuoteLine> ElectronicRequestForQuoteLines { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<Kit> Kits { get; set; }
        public virtual KitComponentsShowType KitComponentsShowType { get; set; }
        public virtual PriceType PriceType { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual ICollection<QuoteAssembly> QuoteAssemblies { get; set; }
        public virtual RequestForQuote RequestForQuote { get; set; }
        public virtual UnitOfMeasureSet UnitOfMeasureSet { get; set; }
        public virtual UnitOfMeasureSet UnitOfMeasureSet1 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<RequestForQuoteLineQuantity> RequestForQuoteLineQuantities { get; set; }
        public virtual ICollection<TaskJournal> TaskJournals { get; set; }
    }
}
