//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityGroupModulePermission
    {
        public int SecurityGroupModulePermissionPK { get; set; }
        public Nullable<int> SecurityGroupModuleFK { get; set; }
        public Nullable<int> ModulePermissionFK { get; set; }
        public Nullable<bool> AccessPrivilege { get; set; }
        public Nullable<bool> AddPrivilege { get; set; }
        public Nullable<bool> ModifyPrivilege { get; set; }
        public Nullable<bool> DeletePrivilege { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ModulePermission ModulePermission { get; set; }
        public virtual SecurityGroupModule SecurityGroupModule { get; set; }
    }
}
