//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermMultipleDueDate
    {
        public int TermMultipleDueDatePK { get; set; }
        public Nullable<int> TermNumber { get; set; }
        public Nullable<int> DaysFromShipDate { get; set; }
        public Nullable<int> PercentageOfInvoice { get; set; }
        public byte[] LastAccess { get; set; }
    }
}
