//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeCard
    {
        public TimeCard()
        {
            this.TimeCardTotals = new HashSet<TimeCardTotal>();
            this.TimeClockEntries = new HashSet<TimeClockEntry>();
            this.UserAccrualLogs = new HashSet<UserAccrualLog>();
        }
    
        public int TimeCardPK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> PayrollCycleFK { get; set; }
        public Nullable<int> PayPeriodFK { get; set; }
        public Nullable<int> ShiftFK { get; set; }
        public Nullable<int> DepartmentFK { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<double> HourlyWage { get; set; }
        public Nullable<double> HourlyOverHeadWage { get; set; }
        public string HourlyOverTimeWage { get; set; }
        public Nullable<bool> PostOverrided { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual PayPeriod PayPeriod { get; set; }
        public virtual PayrollCycle PayrollCycle { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TimeCardTotal> TimeCardTotals { get; set; }
        public virtual ICollection<TimeClockEntry> TimeClockEntries { get; set; }
        public virtual ICollection<UserAccrualLog> UserAccrualLogs { get; set; }
    }
}
