//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDivision
    {
        public int UserDivisionPK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public Nullable<int> SecurityGroupFK { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual SecurityGroup SecurityGroup { get; set; }
        public virtual User User { get; set; }
    }
}
