//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ActivityLogs = new HashSet<ActivityLog>();
            this.BillPaymentChecks = new HashSet<BillPaymentCheck>();
            this.BulletinMessages = new HashSet<BulletinMessage>();
            this.BulletinMessageFors = new HashSet<BulletinMessageFor>();
            this.BusinessProcessResults = new HashSet<BusinessProcessResult>();
            this.BusinessProcessResults1 = new HashSet<BusinessProcessResult>();
            this.BusinessProcessResultDetails = new HashSet<BusinessProcessResultDetail>();
            this.BusinessProcessResultDetails1 = new HashSet<BusinessProcessResultDetail>();
            this.BusinessProcessResultDetails2 = new HashSet<BusinessProcessResultDetail>();
            this.BusinessProcessTemplateDetails = new HashSet<BusinessProcessTemplateDetail>();
            this.ContainmentActions = new HashSet<ContainmentAction>();
            this.DivisionParameters = new HashSet<DivisionParameter>();
            this.Documents = new HashSet<Document>();
            this.Documents1 = new HashSet<Document>();
            this.DocumentGroupUsers = new HashSet<DocumentGroupUser>();
            this.EngineeringChangeRequests = new HashSet<EngineeringChangeRequest>();
            this.EngineeringChangeRequests1 = new HashSet<EngineeringChangeRequest>();
            this.EngineeringChangeRequests2 = new HashSet<EngineeringChangeRequest>();
            this.EngineeringChangeRequests3 = new HashSet<EngineeringChangeRequest>();
            this.EngineeringChangeRequests4 = new HashSet<EngineeringChangeRequest>();
            this.GeneralJournalEntryLines = new HashSet<GeneralJournalEntryLine>();
            this.HRAdditionalInfoes = new HashSet<HRAdditionalInfo>();
            this.HRAddresses = new HashSet<HRAddress>();
            this.HRAwards = new HashSet<HRAward>();
            this.HRBenefits = new HashSet<HRBenefit>();
            this.HRCertificates = new HashSet<HRCertificate>();
            this.HRDependents = new HashSet<HRDependent>();
            this.HREducations = new HashSet<HREducation>();
            this.HREmergencyInfoes = new HashSet<HREmergencyInfo>();
            this.HREvaluations = new HashSet<HREvaluation>();
            this.HREvaluations1 = new HashSet<HREvaluation>();
            this.HRTrainings = new HashSet<HRTraining>();
            this.HRWarnings = new HashSet<HRWarning>();
            this.HRWarnings1 = new HashSet<HRWarning>();
            this.HRWorkHistories = new HashSet<HRWorkHistory>();
            this.Items = new HashSet<Item>();
            this.ItemInventoryTransactions = new HashSet<ItemInventoryTransaction>();
            this.LockedFiles = new HashSet<LockedFile>();
            this.Machines = new HashSet<Machine>();
            this.Machines1 = new HashSet<Machine>();
            this.Machines2 = new HashSet<Machine>();
            this.MachineMaintenanceSchedules = new HashSet<MachineMaintenanceSchedule>();
            this.MachineMaintenanceSchedules1 = new HashSet<MachineMaintenanceSchedule>();
            this.MachineMaintenanceSchedules2 = new HashSet<MachineMaintenanceSchedule>();
            this.MachineMaintenanceScheduleRequests = new HashSet<MachineMaintenanceScheduleRequest>();
            this.MachineMaintenanceScheduleRequests1 = new HashSet<MachineMaintenanceScheduleRequest>();
            this.MachineMaintenanceScheduleRequests2 = new HashSet<MachineMaintenanceScheduleRequest>();
            this.MachineMaintenanceScheduleWorkOrders = new HashSet<MachineMaintenanceScheduleWorkOrder>();
            this.MachineMaintenanceScheduleWorkOrders1 = new HashSet<MachineMaintenanceScheduleWorkOrder>();
            this.MachineMaintenanceScheduleWorkOrders2 = new HashSet<MachineMaintenanceScheduleWorkOrder>();
            this.MachineMaintenanceScheduleWorkOrderActivities = new HashSet<MachineMaintenanceScheduleWorkOrderActivity>();
            this.Manifests = new HashSet<Manifest>();
            this.ManifestLoads = new HashSet<ManifestLoad>();
            this.ManifestLoads1 = new HashSet<ManifestLoad>();
            this.Parties = new HashSet<Party>();
            this.PartyUserNotes = new HashSet<PartyUserNote>();
            this.PickLists = new HashSet<PickList>();
            this.Projects = new HashSet<Project>();
            this.Projects1 = new HashSet<Project>();
            this.Projects2 = new HashSet<Project>();
            this.Projects3 = new HashSet<Project>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseOrders1 = new HashSet<PurchaseOrder>();
            this.PurchaseOrderReceivingLines = new HashSet<PurchaseOrderReceivingLine>();
            this.PurchaseOrderRequests = new HashSet<PurchaseOrderRequest>();
            this.PurchaseOrderRequests1 = new HashSet<PurchaseOrderRequest>();
            this.PurchaseOrderRequests2 = new HashSet<PurchaseOrderRequest>();
            this.PurchaseRFQs = new HashSet<PurchaseRFQ>();
            this.QualityControls = new HashSet<QualityControl>();
            this.QualityControls1 = new HashSet<QualityControl>();
            this.QualityControls2 = new HashSet<QualityControl>();
            this.QualityControls3 = new HashSet<QualityControl>();
            this.QualityControls4 = new HashSet<QualityControl>();
            this.QualityControls5 = new HashSet<QualityControl>();
            this.QualityControls6 = new HashSet<QualityControl>();
            this.QualityControls7 = new HashSet<QualityControl>();
            this.QualityControls8 = new HashSet<QualityControl>();
            this.QualityControls9 = new HashSet<QualityControl>();
            this.QualityControls10 = new HashSet<QualityControl>();
            this.QualityControlContainmentActions = new HashSet<QualityControlContainmentAction>();
            this.QuickViews = new HashSet<QuickView>();
            this.QuickViewMasters = new HashSet<QuickViewMaster>();
            this.QuickViewUsers = new HashSet<QuickViewUser>();
            this.Quotes = new HashSet<Quote>();
            this.Quotes1 = new HashSet<Quote>();
            this.ReportDivisionUsers = new HashSet<ReportDivisionUser>();
            this.ReportFilterCriterias = new HashSet<ReportFilterCriteria>();
            this.RequestForQuotes = new HashSet<RequestForQuote>();
            this.RequestForQuotes1 = new HashSet<RequestForQuote>();
            this.RequestForQuoteLines = new HashSet<RequestForQuoteLine>();
            this.Routers = new HashSet<Router>();
            this.Routers1 = new HashSet<Router>();
            this.SalesOrderCorrespondances = new HashSet<SalesOrderCorrespondance>();
            this.ScheduleDetails = new HashSet<ScheduleDetail>();
            this.ScheduleDetailEmployees = new HashSet<ScheduleDetailEmployee>();
            this.TaskActivities = new HashSet<TaskActivity>();
            this.TaskActivities1 = new HashSet<TaskActivity>();
            this.TaskJournals = new HashSet<TaskJournal>();
            this.TaskWorkFlows = new HashSet<TaskWorkFlow>();
            this.TaskWorkFlowTemplateDetails = new HashSet<TaskWorkFlowTemplateDetail>();
            this.TimeCards = new HashSet<TimeCard>();
            this.TimeClockEntries = new HashSet<TimeClockEntry>();
            this.User1 = new HashSet<User>();
            this.User11 = new HashSet<User>();
            this.User12 = new HashSet<User>();
            this.User13 = new HashSet<User>();
            this.UserAccruals = new HashSet<UserAccrual>();
            this.UserAccrualLogs = new HashSet<UserAccrualLog>();
            this.UserDivisions = new HashSet<UserDivision>();
            this.UserStartupWidgets = new HashSet<UserStartupWidget>();
            this.ViewLogs = new HashSet<ViewLog>();
            this.WorkCenterEmployees = new HashSet<WorkCenterEmployee>();
            this.WorkOrderAssemblies = new HashSet<WorkOrderAssembly>();
            this.WorkOrderCollections = new HashSet<WorkOrderCollection>();
            this.WorkOrderCompletions = new HashSet<WorkOrderCompletion>();
            this.WorkOrderIssuings = new HashSet<WorkOrderIssuing>();
            this.WorkOrderNests = new HashSet<WorkOrderNest>();
            this.WorkOrderProgramCollections = new HashSet<WorkOrderProgramCollection>();
        }
    
        public int UserPK { get; set; }
        public Nullable<int> AddressFK { get; set; }
        public Nullable<int> CellFK { get; set; }
        public Nullable<int> DepartmentFK { get; set; }
        public Nullable<int> EmploymentTypeFK { get; set; }
        public Nullable<int> UserCodeItemFK { get; set; }
        public Nullable<int> OrganizationFK { get; set; }
        public Nullable<int> PayrollCycleFK { get; set; }
        public Nullable<int> PictureFK { get; set; }
        public Nullable<int> ShiftFK { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<bool> AccountExpired { get; set; }
        public Nullable<bool> AccountLocked { get; set; }
        public Nullable<bool> CredentialsExpired { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<bool> EnableEmployeeToWorkOnMultipleJobs { get; set; }
        public Nullable<bool> Estimator { get; set; }
        public Nullable<bool> Inspector { get; set; }
        public Nullable<bool> Planner { get; set; }
        public Nullable<bool> Buyer { get; set; }
        public Nullable<bool> RequireKioskLogIn { get; set; }
        public Nullable<bool> KioskOnly { get; set; }
        public Nullable<bool> Salary { get; set; }
        public Nullable<bool> ShowInTimeKeeper { get; set; }
        public Nullable<bool> Supervisor { get; set; }
        public Nullable<bool> Temporary { get; set; }
        public Nullable<bool> UserDefinedBit1 { get; set; }
        public Nullable<bool> UserDefinedBit2 { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> HiredDate { get; set; }
        public Nullable<System.DateTime> LastChangedPasswordDate { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public Nullable<System.DateTime> SpouseDateOfBirth { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<System.DateTime> TemporaryHireDate { get; set; }
        public Nullable<System.DateTime> LastReviewDate { get; set; }
        public Nullable<System.DateTime> LastRaiseDate { get; set; }
        public string Cell1 { get; set; }
        public string Cell2 { get; set; }
        public string Code { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FormerName { get; set; }
        public string SSN { get; set; }
        public string SpouseName { get; set; }
        public string SpouseSSN { get; set; }
        public string ServiceName { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string EmailAlt { get; set; }
        public string EmailPassword { get; set; }
        public string Password { get; set; }
        public string ConfirmationCode { get; set; }
        public string UserDefinedChar1 { get; set; }
        public string UserDefinedChar2 { get; set; }
        public Nullable<decimal> Wage { get; set; }
        public Nullable<decimal> OvertimeWage { get; set; }
        public Nullable<decimal> Overhead { get; set; }
        public Nullable<bool> PurchaseOrderRequestApprovalRequired { get; set; }
        public Nullable<int> PurchaseOrderRequestApprovalByFK { get; set; }
        public Nullable<decimal> PurchaseOrderApproveAmount1 { get; set; }
        public Nullable<decimal> PurchaseOrderApproveAmount2 { get; set; }
        public Nullable<decimal> PurchaseOrderApproveAmount3 { get; set; }
        public Nullable<int> PurchaseOrderApproveAmount1ByFK { get; set; }
        public Nullable<int> PurchaseOrderApproveAmount2ByFK { get; set; }
        public Nullable<int> PurchaseOrderApproveAmount3ByFK { get; set; }
        public string Comment { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<bool> ExcludeFromProductionOverview { get; set; }
    
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
        public virtual Address Address { get; set; }
        public virtual ICollection<BillPaymentCheck> BillPaymentChecks { get; set; }
        public virtual ICollection<BulletinMessage> BulletinMessages { get; set; }
        public virtual ICollection<BulletinMessageFor> BulletinMessageFors { get; set; }
        public virtual ICollection<BusinessProcessResult> BusinessProcessResults { get; set; }
        public virtual ICollection<BusinessProcessResult> BusinessProcessResults1 { get; set; }
        public virtual ICollection<BusinessProcessResultDetail> BusinessProcessResultDetails { get; set; }
        public virtual ICollection<BusinessProcessResultDetail> BusinessProcessResultDetails1 { get; set; }
        public virtual ICollection<BusinessProcessResultDetail> BusinessProcessResultDetails2 { get; set; }
        public virtual ICollection<BusinessProcessTemplateDetail> BusinessProcessTemplateDetails { get; set; }
        public virtual Cell Cell { get; set; }
        public virtual ICollection<ContainmentAction> ContainmentActions { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<DivisionParameter> DivisionParameters { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Document> Documents1 { get; set; }
        public virtual ICollection<DocumentGroupUser> DocumentGroupUsers { get; set; }
        public virtual EmploymentType EmploymentType { get; set; }
        public virtual ICollection<EngineeringChangeRequest> EngineeringChangeRequests { get; set; }
        public virtual ICollection<EngineeringChangeRequest> EngineeringChangeRequests1 { get; set; }
        public virtual ICollection<EngineeringChangeRequest> EngineeringChangeRequests2 { get; set; }
        public virtual ICollection<EngineeringChangeRequest> EngineeringChangeRequests3 { get; set; }
        public virtual ICollection<EngineeringChangeRequest> EngineeringChangeRequests4 { get; set; }
        public virtual ICollection<GeneralJournalEntryLine> GeneralJournalEntryLines { get; set; }
        public virtual ICollection<HRAdditionalInfo> HRAdditionalInfoes { get; set; }
        public virtual ICollection<HRAddress> HRAddresses { get; set; }
        public virtual ICollection<HRAward> HRAwards { get; set; }
        public virtual ICollection<HRBenefit> HRBenefits { get; set; }
        public virtual ICollection<HRCertificate> HRCertificates { get; set; }
        public virtual ICollection<HRDependent> HRDependents { get; set; }
        public virtual ICollection<HREducation> HREducations { get; set; }
        public virtual ICollection<HREmergencyInfo> HREmergencyInfoes { get; set; }
        public virtual ICollection<HREvaluation> HREvaluations { get; set; }
        public virtual ICollection<HREvaluation> HREvaluations1 { get; set; }
        public virtual ICollection<HRTraining> HRTrainings { get; set; }
        public virtual ICollection<HRWarning> HRWarnings { get; set; }
        public virtual ICollection<HRWarning> HRWarnings1 { get; set; }
        public virtual ICollection<HRWorkHistory> HRWorkHistories { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<ItemInventoryTransaction> ItemInventoryTransactions { get; set; }
        public virtual ICollection<LockedFile> LockedFiles { get; set; }
        public virtual ICollection<Machine> Machines { get; set; }
        public virtual ICollection<Machine> Machines1 { get; set; }
        public virtual ICollection<Machine> Machines2 { get; set; }
        public virtual ICollection<MachineMaintenanceSchedule> MachineMaintenanceSchedules { get; set; }
        public virtual ICollection<MachineMaintenanceSchedule> MachineMaintenanceSchedules1 { get; set; }
        public virtual ICollection<MachineMaintenanceSchedule> MachineMaintenanceSchedules2 { get; set; }
        public virtual ICollection<MachineMaintenanceScheduleRequest> MachineMaintenanceScheduleRequests { get; set; }
        public virtual ICollection<MachineMaintenanceScheduleRequest> MachineMaintenanceScheduleRequests1 { get; set; }
        public virtual ICollection<MachineMaintenanceScheduleRequest> MachineMaintenanceScheduleRequests2 { get; set; }
        public virtual ICollection<MachineMaintenanceScheduleWorkOrder> MachineMaintenanceScheduleWorkOrders { get; set; }
        public virtual ICollection<MachineMaintenanceScheduleWorkOrder> MachineMaintenanceScheduleWorkOrders1 { get; set; }
        public virtual ICollection<MachineMaintenanceScheduleWorkOrder> MachineMaintenanceScheduleWorkOrders2 { get; set; }
        public virtual ICollection<MachineMaintenanceScheduleWorkOrderActivity> MachineMaintenanceScheduleWorkOrderActivities { get; set; }
        public virtual ICollection<Manifest> Manifests { get; set; }
        public virtual ICollection<ManifestLoad> ManifestLoads { get; set; }
        public virtual ICollection<ManifestLoad> ManifestLoads1 { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Party> Parties { get; set; }
        public virtual ICollection<PartyUserNote> PartyUserNotes { get; set; }
        public virtual PayrollCycle PayrollCycle { get; set; }
        public virtual ICollection<PickList> PickLists { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Project> Projects1 { get; set; }
        public virtual ICollection<Project> Projects2 { get; set; }
        public virtual ICollection<Project> Projects3 { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders1 { get; set; }
        public virtual ICollection<PurchaseOrderReceivingLine> PurchaseOrderReceivingLines { get; set; }
        public virtual ICollection<PurchaseOrderRequest> PurchaseOrderRequests { get; set; }
        public virtual ICollection<PurchaseOrderRequest> PurchaseOrderRequests1 { get; set; }
        public virtual ICollection<PurchaseOrderRequest> PurchaseOrderRequests2 { get; set; }
        public virtual ICollection<PurchaseRFQ> PurchaseRFQs { get; set; }
        public virtual ICollection<QualityControl> QualityControls { get; set; }
        public virtual ICollection<QualityControl> QualityControls1 { get; set; }
        public virtual ICollection<QualityControl> QualityControls2 { get; set; }
        public virtual ICollection<QualityControl> QualityControls3 { get; set; }
        public virtual ICollection<QualityControl> QualityControls4 { get; set; }
        public virtual ICollection<QualityControl> QualityControls5 { get; set; }
        public virtual ICollection<QualityControl> QualityControls6 { get; set; }
        public virtual ICollection<QualityControl> QualityControls7 { get; set; }
        public virtual ICollection<QualityControl> QualityControls8 { get; set; }
        public virtual ICollection<QualityControl> QualityControls9 { get; set; }
        public virtual ICollection<QualityControl> QualityControls10 { get; set; }
        public virtual ICollection<QualityControlContainmentAction> QualityControlContainmentActions { get; set; }
        public virtual ICollection<QuickView> QuickViews { get; set; }
        public virtual ICollection<QuickViewMaster> QuickViewMasters { get; set; }
        public virtual ICollection<QuickViewUser> QuickViewUsers { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<Quote> Quotes1 { get; set; }
        public virtual ICollection<ReportDivisionUser> ReportDivisionUsers { get; set; }
        public virtual ICollection<ReportFilterCriteria> ReportFilterCriterias { get; set; }
        public virtual ICollection<RequestForQuote> RequestForQuotes { get; set; }
        public virtual ICollection<RequestForQuote> RequestForQuotes1 { get; set; }
        public virtual ICollection<RequestForQuoteLine> RequestForQuoteLines { get; set; }
        public virtual ICollection<Router> Routers { get; set; }
        public virtual ICollection<Router> Routers1 { get; set; }
        public virtual ICollection<SalesOrderCorrespondance> SalesOrderCorrespondances { get; set; }
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
        public virtual ICollection<ScheduleDetailEmployee> ScheduleDetailEmployees { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual ICollection<TaskActivity> TaskActivities { get; set; }
        public virtual ICollection<TaskActivity> TaskActivities1 { get; set; }
        public virtual ICollection<TaskJournal> TaskJournals { get; set; }
        public virtual ICollection<TaskWorkFlow> TaskWorkFlows { get; set; }
        public virtual ICollection<TaskWorkFlowTemplateDetail> TaskWorkFlowTemplateDetails { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual ICollection<TimeClockEntry> TimeClockEntries { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<User> User11 { get; set; }
        public virtual User User3 { get; set; }
        public virtual ICollection<User> User12 { get; set; }
        public virtual User User4 { get; set; }
        public virtual ICollection<User> User13 { get; set; }
        public virtual User User5 { get; set; }
        public virtual User User14 { get; set; }
        public virtual User User6 { get; set; }
        public virtual ICollection<UserAccrual> UserAccruals { get; set; }
        public virtual ICollection<UserAccrualLog> UserAccrualLogs { get; set; }
        public virtual UserCodeItem UserCodeItem { get; set; }
        public virtual ICollection<UserDivision> UserDivisions { get; set; }
        public virtual ICollection<UserStartupWidget> UserStartupWidgets { get; set; }
        public virtual ICollection<ViewLog> ViewLogs { get; set; }
        public virtual ICollection<WorkCenterEmployee> WorkCenterEmployees { get; set; }
        public virtual ICollection<WorkOrderAssembly> WorkOrderAssemblies { get; set; }
        public virtual ICollection<WorkOrderCollection> WorkOrderCollections { get; set; }
        public virtual ICollection<WorkOrderCompletion> WorkOrderCompletions { get; set; }
        public virtual ICollection<WorkOrderIssuing> WorkOrderIssuings { get; set; }
        public virtual ICollection<WorkOrderNest> WorkOrderNests { get; set; }
        public virtual ICollection<WorkOrderProgramCollection> WorkOrderProgramCollections { get; set; }
    }
}
