//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCodeItem
    {
        public UserCodeItem()
        {
            this.HRAwards = new HashSet<HRAward>();
            this.HRBenefits = new HashSet<HRBenefit>();
            this.HRCertificates = new HashSet<HRCertificate>();
            this.HRDependents = new HashSet<HRDependent>();
            this.HRDependents1 = new HashSet<HRDependent>();
            this.HREducations = new HashSet<HREducation>();
            this.HREducations1 = new HashSet<HREducation>();
            this.HREmergencyInfoes = new HashSet<HREmergencyInfo>();
            this.HRTrainings = new HashSet<HRTraining>();
            this.HRTrainings1 = new HashSet<HRTraining>();
            this.HRTrainings2 = new HashSet<HRTraining>();
            this.HRWarnings = new HashSet<HRWarning>();
            this.Users = new HashSet<User>();
        }
    
        public int UserCodeItemPK { get; set; }
        public int UserCodeCategoryFK { get; set; }
        public string Code { get; set; }
        public int OrderIndex { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserCodeItemNumber { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<HRAward> HRAwards { get; set; }
        public virtual ICollection<HRBenefit> HRBenefits { get; set; }
        public virtual ICollection<HRCertificate> HRCertificates { get; set; }
        public virtual ICollection<HRDependent> HRDependents { get; set; }
        public virtual ICollection<HRDependent> HRDependents1 { get; set; }
        public virtual ICollection<HREducation> HREducations { get; set; }
        public virtual ICollection<HREducation> HREducations1 { get; set; }
        public virtual ICollection<HREmergencyInfo> HREmergencyInfoes { get; set; }
        public virtual ICollection<HRTraining> HRTrainings { get; set; }
        public virtual ICollection<HRTraining> HRTrainings1 { get; set; }
        public virtual ICollection<HRTraining> HRTrainings2 { get; set; }
        public virtual ICollection<HRWarning> HRWarnings { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual UserCodeCategory UserCodeCategory { get; set; }
    }
}
