//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderNestJob
    {
        public int WorkOrderNestJobPK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> ItemMachineFK { get; set; }
        public Nullable<int> MaterialItemFK { get; set; }
        public Nullable<int> WorkOrderNestStatusFK { get; set; }
        public Nullable<decimal> StockWidth { get; set; }
        public Nullable<decimal> StockLength { get; set; }
        public Nullable<int> RouterNumber { get; set; }
        public Nullable<int> SalesOrderNumber { get; set; }
        public Nullable<int> JobNumber { get; set; }
        public Nullable<int> WorkOrderNumber { get; set; }
        public Nullable<int> ReleaseNumber { get; set; }
        public Nullable<int> WorkOrderAssemblyNumber { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string DXFFile { get; set; }
        public string NestName { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual ItemMachine ItemMachine { get; set; }
        public virtual WorkOrderNestJob WorkOrderNestJob1 { get; set; }
        public virtual WorkOrderNestJob WorkOrderNestJob2 { get; set; }
        public virtual WorkOrderNestStatu WorkOrderNestStatu { get; set; }
    }
}
