//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderJob
    {
        public int WorkOrderJobPK { get; set; }
        public Nullable<int> WorkOrderFK { get; set; }
        public Nullable<int> SalesOrderFK { get; set; }
        public Nullable<int> SalesOrderLineFK { get; set; }
        public Nullable<int> SalesOrderLineLotFK { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string SalesOrderNumber { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<int> InvoiceLineNumber { get; set; }
        public Nullable<System.DateTime> InvoiceShipDate { get; set; }
        public string RMANumber { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual SalesOrderLine SalesOrderLine { get; set; }
        public virtual SalesOrderLineLot SalesOrderLineLot { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
