//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderTotal
    {
        public WorkOrderTotal()
        {
            this.WorkOrders = new HashSet<WorkOrder>();
        }
    
        public int WorkOrderTotalPK { get; set; }
        public Nullable<decimal> TotalActualHours { get; set; }
        public Nullable<decimal> TotalReworkHours { get; set; }
        public Nullable<decimal> TotalEstimatedHours { get; set; }
        public Nullable<decimal> DirectLabor { get; set; }
        public Nullable<decimal> DirectLaborRework { get; set; }
        public Nullable<decimal> DirectLaborEstimated { get; set; }
        public Nullable<decimal> EmployeeOverhead { get; set; }
        public Nullable<decimal> EmployeeOverheadRework { get; set; }
        public Nullable<decimal> EmployeeOverheadEstimated { get; set; }
        public Nullable<decimal> WorkCenterOverhead { get; set; }
        public Nullable<decimal> WorkCenterOverheadRework { get; set; }
        public Nullable<decimal> WorkCenterOverheadEstimated { get; set; }
        public Nullable<decimal> MaterialCosts { get; set; }
        public Nullable<decimal> HardwareCostsRework { get; set; }
        public Nullable<decimal> MaterialCostsEstimated { get; set; }
        public Nullable<decimal> HardwareCosts { get; set; }
        public Nullable<decimal> MaterialCostsRework { get; set; }
        public Nullable<decimal> HardwareCostsEstimated { get; set; }
        public Nullable<decimal> OutsideProcessingCosts { get; set; }
        public Nullable<decimal> OutsideProcessingCostsRework { get; set; }
        public Nullable<decimal> OutsideProcessingCostsEstimated { get; set; }
        public Nullable<decimal> ProductCosts { get; set; }
        public Nullable<decimal> ProductCostsRework { get; set; }
        public Nullable<decimal> ProductCostsEstimated { get; set; }
        public Nullable<decimal> SalesCommissions { get; set; }
        public Nullable<decimal> SalesCommissionsRework { get; set; }
        public Nullable<decimal> SalesCommissionsEstimated { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<decimal> ProfitEstimated { get; set; }
        public Nullable<decimal> ProfitRework { get; set; }
        public Nullable<decimal> QuantityCompleted { get; set; }
        public Nullable<decimal> SalesRevenues { get; set; }
        public Nullable<decimal> SalesRevenuesEstimated { get; set; }
        public Nullable<decimal> SalesRevenuesRework { get; set; }
        public Nullable<decimal> HoursLeft { get; set; }
        public Nullable<System.DateTime> LastWorkedDate { get; set; }
        public Nullable<System.DateTime> LastTransactionDate { get; set; }
        public Nullable<System.DateTime> LastLaborCollectionDate { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
    }
}
