//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderCompletion
    {
        public int WorkOrderCompletionPK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> WorkOrderFK { get; set; }
        public Nullable<int> WorkOrderReleaseFK { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Scrap { get; set; }
        public string LotNumber { get; set; }
        public string Location { get; set; }
        public string Comments { get; set; }
        public byte[] LastAccess { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual WorkOrderRelease WorkOrderRelease { get; set; }
    }
}
