//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderRelease
    {
        public WorkOrderRelease()
        {
            this.MRPDetails = new HashSet<MRPDetail>();
            this.ScheduleDetails = new HashSet<ScheduleDetail>();
            this.WorkOrderAssemblies = new HashSet<WorkOrderAssembly>();
            this.WorkOrderCompletions = new HashSet<WorkOrderCompletion>();
        }
    
        public int WorkOrderReleasePK { get; set; }
        public Nullable<int> WorkOrderFK { get; set; }
        public Nullable<int> HardwareItemFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> MaterialItemFK { get; set; }
        public Nullable<int> OutsideProcessingItemFK { get; set; }
        public Nullable<int> ParentRouterFK { get; set; }
        public Nullable<int> RouterFK { get; set; }
        public Nullable<int> RouterWorkCenterFK { get; set; }
        public Nullable<int> CellFK { get; set; }
        public Nullable<int> RunNumber { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<bool> Released { get; set; }
        public Nullable<bool> Nested { get; set; }
        public Nullable<bool> CellCompleted { get; set; }
        public string HardwareDescription { get; set; }
        public string MaterialDescription { get; set; }
        public string OutsideProcessingDescription { get; set; }
        public string CurrentLocation { get; set; }
        public string Revision { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<decimal> CellEstimatedHours { get; set; }
        public Nullable<decimal> CellActualHours { get; set; }
        public Nullable<decimal> CellBottleneckHours { get; set; }
        public Nullable<decimal> QuantityHardware { get; set; }
        public Nullable<decimal> QuantityMaterial { get; set; }
        public Nullable<decimal> QuantityOutsideProcessing { get; set; }
        public Nullable<decimal> QuantityRequired { get; set; }
        public Nullable<decimal> QuantityShipped { get; set; }
        public Nullable<decimal> QuantityToFabricate { get; set; }
        public Nullable<decimal> QuantityToPull { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> AssemblyLevel { get; set; }
        public Nullable<bool> CellScheduled { get; set; }
        public Nullable<System.DateTime> CellCompletedDate { get; set; }
        public Nullable<bool> Printed { get; set; }
        public Nullable<decimal> QuantityParentShipped { get; set; }
    
        public virtual Cell Cell { get; set; }
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual Item Item2 { get; set; }
        public virtual Item Item3 { get; set; }
        public virtual ICollection<MRPDetail> MRPDetails { get; set; }
        public virtual Router Router { get; set; }
        public virtual Router Router1 { get; set; }
        public virtual RouterWorkCenter RouterWorkCenter { get; set; }
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual ICollection<WorkOrderAssembly> WorkOrderAssemblies { get; set; }
        public virtual ICollection<WorkOrderCompletion> WorkOrderCompletions { get; set; }
    }
}
