//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderNest
    {
        public WorkOrderNest()
        {
            this.Documents = new HashSet<Document>();
            this.WorkOrderPrograms = new HashSet<WorkOrderProgram>();
        }
    
        public int WorkOrderNestPK { get; set; }
        public Nullable<int> DivisionFK { get; set; }
        public Nullable<int> ProgrammerFK { get; set; }
        public Nullable<int> WorkOrderNestStatusFK { get; set; }
        public string WorkOrderNestNumber { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateReadyToProgram { get; set; }
        public Nullable<System.DateTime> DateReadyToRun { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> ActualHours { get; set; }
        public Nullable<decimal> EstimatedHours { get; set; }
        public Nullable<decimal> ActualBillOfMaterialCosts { get; set; }
        public Nullable<decimal> ActualLaborCosts { get; set; }
        public Nullable<decimal> EstimatedBillOfMaterialCosts { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<int> NestJobId { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual User User { get; set; }
        public virtual WorkOrderNestStatu WorkOrderNestStatu { get; set; }
        public virtual ICollection<WorkOrderProgram> WorkOrderPrograms { get; set; }
    }
}
