//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MieTrakWrapper.MieTrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderAssembly
    {
        public WorkOrderAssembly()
        {
            this.PurchaseOrderLineRequirements = new HashSet<PurchaseOrderLineRequirement>();
            this.ScheduleDetails = new HashSet<ScheduleDetail>();
        }
    
        public int WorkOrderAssemblyPK { get; set; }
        public Nullable<int> WorkOrderFK { get; set; }
        public Nullable<int> RouterFK { get; set; }
        public Nullable<int> ParentRouterFK { get; set; }
        public Nullable<int> ItemRouterFK { get; set; }
        public Nullable<int> HardwareItemFK { get; set; }
        public Nullable<int> ItemFK { get; set; }
        public Nullable<int> MaterialItemFK { get; set; }
        public Nullable<int> OperationFK { get; set; }
        public Nullable<int> OutsideProcessingItemFK { get; set; }
        public Nullable<int> SupplierFK { get; set; }
        public Nullable<int> UnitOfMeasureSetFK { get; set; }
        public Nullable<int> WorkCenterFK { get; set; }
        public Nullable<int> WorkOrderAssemblyBOMStatusFK { get; set; }
        public Nullable<int> WorkOrderAssemblyLaborStatusFK { get; set; }
        public Nullable<int> WhiteBoardFK { get; set; }
        public Nullable<int> WorkOrderReleaseFK { get; set; }
        public Nullable<int> WorkOrderProgramFK { get; set; }
        public Nullable<int> WorkOrderNestFK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DaysOut { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public Nullable<int> ProductOrder { get; set; }
        public Nullable<int> RunEmployees { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<int> SetupEmployees { get; set; }
        public Nullable<int> SplitMachines { get; set; }
        public Nullable<bool> AgainstGrain { get; set; }
        public Nullable<bool> CertificationsRequired { get; set; }
        public Nullable<bool> DefaultMachinesExist { get; set; }
        public Nullable<bool> DoubleSided { get; set; }
        public Nullable<bool> DropFlag { get; set; }
        public Nullable<bool> IsAddOn { get; set; }
        public Nullable<bool> IsEdited { get; set; }
        public Nullable<bool> IsNested { get; set; }
        public Nullable<bool> Inspected { get; set; }
        public Nullable<bool> Nestable { get; set; }
        public Nullable<bool> NonAmortizedItem { get; set; }
        public Nullable<bool> SetStatusToPullFromInventory { get; set; }
        public Nullable<int> StockPieces { get; set; }
        public Nullable<bool> StopSequence { get; set; }
        public Nullable<bool> UnattendedOperation { get; set; }
        public Nullable<bool> UseExactMaterialCalculation { get; set; }
        public Nullable<System.DateTime> GoodUntil { get; set; }
        public Nullable<System.DateTime> OnDockDate { get; set; }
        public Nullable<System.DateTime> ScheduleStartDateAndTime { get; set; }
        public Nullable<System.DateTime> ScheduleEndDateAndTime { get; set; }
        public Nullable<System.DateTime> PurchaseOrderRequiredDate { get; set; }
        public Nullable<System.DateTime> TargetStartDate { get; set; }
        public Nullable<System.DateTime> TargetDueDate { get; set; }
        public Nullable<bool> GrainDirection { get; set; }
        public string UserFullName { get; set; }
        public string Color { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string HardwareDescription { get; set; }
        public string MaterialDescription { get; set; }
        public string OutsideProcessingDescription { get; set; }
        public string WIPMovementLocation { get; set; }
        public string PartNumber { get; set; }
        public string MachineAssignment { get; set; }
        public string MachinePredecessor { get; set; }
        public Nullable<decimal> PartsPerBlankScrapPercentage { get; set; }
        public Nullable<decimal> OveragePercentage { get; set; }
        public Nullable<decimal> StockPiecesScrapPercentage { get; set; }
        public Nullable<decimal> UnattendedPercentage { get; set; }
        public Nullable<decimal> BatchSize { get; set; }
        public Nullable<decimal> LagTime { get; set; }
        public Nullable<decimal> MinimumPiecePrice { get; set; }
        public Nullable<decimal> PartsPerBlank { get; set; }
        public Nullable<decimal> PartsRequired { get; set; }
        public Nullable<decimal> PieceWeight { get; set; }
        public Nullable<decimal> RouterQuantityRequired { get; set; }
        public Nullable<decimal> QuantityPerInverse { get; set; }
        public Nullable<decimal> MinutesPerPart { get; set; }
        public Nullable<decimal> SetupTime { get; set; }
        public Nullable<decimal> StagingTime { get; set; }
        public Nullable<decimal> TransitTime { get; set; }
        public Nullable<decimal> TearDownTime { get; set; }
        public Nullable<decimal> WaitTime { get; set; }
        public Nullable<decimal> BlankLength { get; set; }
        public Nullable<decimal> BlankWidth { get; set; }
        public Nullable<decimal> Overlap { get; set; }
        public Nullable<decimal> PartLength { get; set; }
        public Nullable<decimal> PartWidth { get; set; }
        public Nullable<decimal> PiecesPerHour { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> SafetyStockLength { get; set; }
        public Nullable<decimal> SafetyStockWidth { get; set; }
        public Nullable<decimal> SquareInchesOrLbsEstimate { get; set; }
        public Nullable<decimal> StockLength { get; set; }
        public Nullable<decimal> StockWidth { get; set; }
        public Nullable<decimal> Thickness { get; set; }
        public Nullable<decimal> Tolerance { get; set; }
        public Nullable<decimal> UserDefined1 { get; set; }
        public Nullable<decimal> UserDefined2 { get; set; }
        public Nullable<decimal> UserDefined3 { get; set; }
        public Nullable<decimal> WeightFactor { get; set; }
        public Nullable<decimal> TotalActualHours { get; set; }
        public Nullable<decimal> TotalEstimatedHours { get; set; }
        public Nullable<decimal> QuantityToFabricate { get; set; }
        public Nullable<decimal> QuantityIssued { get; set; }
        public Nullable<decimal> QuantityOrdered { get; set; }
        public Nullable<decimal> QuantityProduced { get; set; }
        public Nullable<decimal> QuantityPull { get; set; }
        public Nullable<decimal> QuantityReceived { get; set; }
        public Nullable<decimal> QuantityRequired { get; set; }
        public Nullable<decimal> QuantityScrapped { get; set; }
        public Nullable<decimal> TotalQuantityRequired { get; set; }
        public Nullable<decimal> VendorUnit { get; set; }
        public Nullable<decimal> FabricationQuantity1 { get; set; }
        public Nullable<decimal> FabricationQuantity2 { get; set; }
        public Nullable<decimal> FabricationQuantity3 { get; set; }
        public Nullable<decimal> FabricationQuantity4 { get; set; }
        public Nullable<decimal> FabricationQuantity5 { get; set; }
        public Nullable<decimal> ConcurrentSetups1 { get; set; }
        public Nullable<decimal> ConcurrentSetups2 { get; set; }
        public Nullable<decimal> ConcurrentSetups3 { get; set; }
        public Nullable<decimal> ConcurrentSetups4 { get; set; }
        public Nullable<decimal> ConcurrentSetups5 { get; set; }
        public string DrawingNumber { get; set; }
        public string MarkNumber { get; set; }
        public string DefaultMachineNumber { get; set; }
        public string DefaultLocation { get; set; }
        public string Comment { get; set; }
        public string Instructions { get; set; }
        public string ToolingComment { get; set; }
        public Nullable<bool> Released { get; set; }
        public string PriorWorkCenter { get; set; }
        public Nullable<decimal> PriorTotalEstimatedHours { get; set; }
        public string NextWorkCenter { get; set; }
        public Nullable<decimal> NextTotalEstimatedHours { get; set; }
        public byte[] LastAccess { get; set; }
        public Nullable<decimal> DropPercentage { get; set; }
        public string Revision { get; set; }
        public Nullable<int> WorkOrderAssemblySeqNumberFK { get; set; }
        public Nullable<int> ExplodedFromWOAssembly { get; set; }
        public Nullable<bool> Exploded { get; set; }
        public string ProgramNumber { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual Item Item2 { get; set; }
        public virtual Item Item3 { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual Party Party { get; set; }
        public virtual ICollection<PurchaseOrderLineRequirement> PurchaseOrderLineRequirements { get; set; }
        public virtual Router Router { get; set; }
        public virtual Router Router1 { get; set; }
        public virtual Router Router2 { get; set; }
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
        public virtual UnitOfMeasureSet UnitOfMeasureSet { get; set; }
        public virtual User User { get; set; }
        public virtual WorkCenter WorkCenter { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual WorkOrderAssemblyBOMStatu WorkOrderAssemblyBOMStatu { get; set; }
        public virtual WorkOrderAssemblyLaborStatu WorkOrderAssemblyLaborStatu { get; set; }
        public virtual WorkOrderRelease WorkOrderRelease { get; set; }
    }
}
